// Extra example sentences (memory by context). Maps a headword -> array of
// ADDITIONAL English-only sentences. Combined with the word's own `example`
// (in words.js), the card can show several sentences in different contexts
// BEFORE the learner flips to see the Thai meaning.
//
// Kept separate so coverage can grow without touching the main word list.
// Words not listed here still show their single `example` from words.js.
const EXAMPLES = {
  // ---- ขั้นสูง (Advanced) ----
  abundant: ["The garden produced an abundant harvest this year.", "Fresh water is abundant in this region."],
  accomplish: ["She accomplished more in a week than most do in a month.", "With teamwork, we can accomplish almost anything."],
  acknowledge: ["The company acknowledged the error and apologized.", "He nodded to acknowledge her presence."],
  acquire: ["Over time, he acquired a taste for spicy food.", "The museum acquired a rare painting."],
  adequate: ["The salary is adequate for a single person.", "Make sure you get adequate rest before the trip."],
  ambiguous: ["The contract's wording was dangerously ambiguous.", "Her smile was ambiguous — I couldn't read it."],
  anticipate: ["We anticipate heavy traffic during the holidays.", "A good player anticipates the opponent's moves."],
  arbitrary: ["The rule seemed arbitrary and unfair.", "They picked the winner in an arbitrary way."],
  assess: ["The doctor assessed the patient's condition.", "Let's assess the damage before deciding."],
  assume: ["Never assume people know what you mean.", "I assumed the meeting was canceled."],
  authentic: ["The restaurant serves authentic Italian food.", "Experts confirmed the painting was authentic."],
  bias: ["The judge showed no bias toward either side.", "We must remove bias from the hiring process."],
  cease: ["The factory ceased production last year.", "The rain finally ceased at noon."],
  coherent: ["After some sleep, his thoughts became coherent.", "She presented a coherent plan to the board."],
  collaborate: ["Designers and engineers collaborate on every product.", "The two authors collaborated on a novel."],
  compel: ["The evidence compelled them to change their minds.", "Nothing can compel me to lie."],
  competent: ["She is a highly competent surgeon.", "You need a competent lawyer for this case."],
  comprehensive: ["The book is a comprehensive guide to gardening.", "We need a comprehensive review of the system."],
  consequence: ["He didn't think about the consequences of his actions.", "As a consequence, the project was delayed."],
  consistent: ["Her grades have been consistent all year.", "A consistent routine improves sleep."],
  contemplate: ["He sat by the lake, contemplating his future.", "We're contemplating a move to another city."],
  controversial: ["The new law is highly controversial.", "She made a controversial decision."],
  convey: ["The teacher used images to convey the idea.", "Please convey my thanks to your team."],
  crucial: ["The next few days are crucial for the campaign.", "Sleep is crucial to recovery."],
  deliberate: ["It was a deliberate attempt to mislead us.", "She spoke in a slow, deliberate voice."],
  demonstrate: ["The study demonstrates a clear link.", "Let me demonstrate the correct technique."],
  deteriorate: ["His eyesight deteriorated with age.", "Relations between the two sides deteriorated."],
  diligent: ["A diligent worker checks every detail.", "Her diligent research paid off."],
  diminish: ["The pain gradually diminished.", "Nothing could diminish her enthusiasm."],
  distinct: ["There are three distinct stages to the process.", "The two brothers have distinct personalities."],
  diverse: ["The city has a diverse population.", "We offer a diverse range of products."],
  dubious: ["He made a dubious claim about his past.", "I'm dubious about the benefits of the diet."],
  eligible: ["Only members are eligible for the discount.", "She is eligible to vote this year."],
  emerge: ["A new leader emerged from the crisis.", "The sun emerged from behind the clouds."],
  enhance: ["Good lighting enhances the photo.", "The update enhances the app's speed."],
  evident: ["It was evident that she had been crying.", "His talent is evident in every painting."],
  exceed: ["The results exceeded all expectations.", "Don't exceed the speed limit."],
  explicit: ["He gave explicit instructions.", "The map shows the route in explicit detail."],
  feasible: ["Is it feasible to finish by Friday?", "They studied whether the plan was feasible."],
  fundamental: ["Honesty is fundamental to trust.", "There's a fundamental flaw in the design."],
  genuine: ["She showed genuine interest in the topic.", "Is this a genuine leather bag?"],
  hinder: ["Heavy snow hindered the rescue effort.", "Don't let fear hinder your progress."],
  impose: ["The city imposed a curfew.", "I don't want to impose on your time."],
  inevitable: ["With such effort, success was inevitable.", "Aging is an inevitable part of life."],
  inherent: ["There are inherent dangers in the sport.", "Curiosity is inherent in children."],
  mitigate: ["Planting trees can mitigate flooding.", "We took steps to mitigate the risk."],
  notorious: ["The road is notorious for accidents.", "He's notorious for arriving late."],
  optimal: ["Find the optimal route to save fuel.", "Water the plants at the optimal time."],
  plausible: ["She gave a plausible excuse.", "It's a plausible theory, but unproven."],
  pragmatic: ["We need a pragmatic solution, not a perfect one.", "She took a pragmatic approach to the budget."],
  profound: ["The book had a profound effect on me.", "He spoke with profound sadness."],
  prominent: ["She's a prominent figure in science.", "The sign was placed in a prominent spot."],
  reluctant: ["He was reluctant to admit his mistake.", "She gave a reluctant nod."],
  resilient: ["The economy proved surprisingly resilient.", "Children are remarkably resilient."],
  rigorous: ["The product passed rigorous testing.", "She follows a rigorous training schedule."],
  subtle: ["There's a subtle hint of lemon in the sauce.", "He made a subtle change to the design."],
  sufficient: ["We have sufficient evidence to proceed.", "One example is not sufficient."],
  sustain: ["The bridge can sustain heavy loads.", "It's hard to sustain that pace."],
  tedious: ["Filling out forms is tedious work.", "The lecture was long and tedious."],
  thorough: ["She gave the room a thorough cleaning.", "We need a thorough investigation."],
  trivial: ["Don't argue over trivial details.", "The cost is trivial compared to the benefit."],
  versatile: ["A smartphone is a versatile tool.", "She's a versatile player who can fill any role."],
  viable: ["Solar power is now a viable option.", "Is the business model viable?"],
  vivid: ["She has vivid memories of childhood.", "The sunset was a vivid orange."],
  vulnerable: ["The elderly are vulnerable to the cold.", "He felt vulnerable after the loss."],

  // ---- ธุรกิจ (Business) ----
  invoice: ["We'll issue the invoice once the work is done.", "The invoice is due within 30 days."],
  quotation: ["Could you send a quotation for 500 units?", "The quotation does not include shipping."],
  budget: ["The marketing budget was cut this year.", "We finished the project under budget."],
  revenue: ["Online sales boosted our revenue.", "Revenue fell sharply last quarter."],
  profit: ["The store made a small profit last month.", "They sold the company for a huge profit."],
  refund: ["You can get a full refund within 14 days.", "They refused to give me a refund."],
  overdue: ["The payment is now overdue.", "The library book is two days overdue."],
  supplier: ["We switched to a cheaper supplier.", "Our main supplier is overseas."],
  "on behalf of": ["I'm signing on behalf of the director.", "She accepted the award on behalf of the team."],

  // ---- ระดับกลาง (Intermediate) ----
  afford: ["We can't afford to make mistakes.", "Can you afford the rent on your own?"],
  avoid: ["Avoid the highway during rush hour.", "She avoided eye contact."],
  improve: ["His English improved quickly.", "We're always looking to improve."],
  suggest: ["I suggest we take a break.", "The data suggests a different conclusion."],
  depend: ["It depends on what you want.", "Many families depend on this factory."],

  // ---- ขั้นสูง (Advanced) — ที่เหลือ จนครบ 210 ----
  accurate: ["The clock is accurate to the second.", "Make sure your report is accurate."],
  advocate: ["She advocates for cleaner energy.", "He is a strong advocate of free education."],
  aesthetic: ["The room has a minimalist aesthetic.", "They chose the design for aesthetic reasons."],
  allocate: ["The government allocated funds for schools.", "We allocate two hours a day to training."],
  analyze: ["Researchers analyze the samples in the lab.", "Let's analyze why the sales dropped."],
  apparent: ["For no apparent reason, the engine stopped.", "It soon became apparent that he was lost."],
  articulate: ["She can articulate complex ideas simply.", "He's an articulate and confident speaker."],
  aspire: ["Many young athletes aspire to the Olympics.", "She aspires to lead the company one day."],
  attain: ["Few runners attain such a fast time.", "He worked hard to attain his goals."],
  benevolent: ["A benevolent donor paid for the hospital.", "She gave a benevolent smile to the child."],
  boost: ["The win gave the team a huge boost.", "Exercise can boost your energy levels."],
  brilliant: ["She came up with a brilliant solution.", "The diamond gave off a brilliant light."],
  candid: ["He was candid about his weaknesses.", "I appreciate your candid opinion."],
  capacity: ["The stadium has a capacity of 50,000.", "She has a great capacity for hard work."],
  coincide: ["My visit will coincide with the festival.", "Their views coincide on most issues."],
  commence: ["The trial will commence next Monday.", "Work on the bridge commenced in March."],
  compensate: ["The airline compensated us for the delay.", "Hard work can compensate for a lack of talent."],
  compromise: ["Neither side would compromise.", "They reached a fair compromise."],
  conceive: ["It's hard to conceive of life without phones.", "She conceived the idea while traveling."],
  concise: ["Please keep your summary concise.", "His concise report saved everyone time."],
  condemn: ["World leaders condemned the attack.", "The building was condemned as unsafe."],
  conform: ["New products must conform to the rules.", "He refused to conform to the trend."],
  consensus: ["The team reached a consensus quickly.", "There is no consensus on the cause."],
  conserve: ["Turn off lights to conserve energy.", "The park was created to conserve wildlife."],
  considerable: ["The repairs cost a considerable amount.", "She has considerable experience in law."],
  conspicuous: ["His bright jacket made him conspicuous.", "She felt conspicuous in the quiet room."],
  constitute: ["Twelve members constitute the committee.", "Such acts constitute a serious crime."],
  contradict: ["The witness contradicted herself.", "These results contradict the earlier study."],
  cope: ["She couldn't cope with the pressure.", "How do you cope with stress at work?"],
  cumulative: ["The cumulative effect of small savings is huge.", "Stress can have a cumulative impact on health."],
  curb: ["The new rules aim to curb pollution.", "He tried to curb his spending."],
  deduce: ["From the clues, she deduced the answer.", "We can deduce his age from the photo."],
  deficient: ["The soil is deficient in nutrients.", "Their plan was deficient in detail."],
  denote: ["A red light denotes danger.", "The symbol denotes a chemical element."],
  devise: ["Engineers devised a clever solution.", "She devised a new way to teach reading."],
  discrepancy: ["There's a discrepancy between the two reports.", "The audit found a discrepancy in the accounts."],
  dominant: ["Lions are the dominant predators here.", "English is the dominant language online."],
  eloquent: ["Her eloquent speech moved the crowd.", "He wrote an eloquent letter of thanks."],
  elaborate: ["They planned an elaborate ceremony.", "Could you elaborate on your idea?"],
  embrace: ["The company embraced new technology.", "They embraced warmly at the airport."],
  eminent: ["An eminent professor gave the lecture.", "She is eminent in the field of medicine."],
  empirical: ["The claim lacks empirical support.", "Scientists rely on empirical data."],
  endeavor: ["We will endeavor to improve our service.", "Space travel is a costly endeavor."],
  endorse: ["Several doctors endorse the product.", "The mayor endorsed the new plan."],
  enormous: ["The project required an enormous effort.", "They live in an enormous house."],
  entitle: ["This pass entitles you to free entry.", "Membership entitles you to discounts."],
  equivalent: ["A mile is equivalent to about 1.6 km.", "His silence was equivalent to a yes."],
  eradicate: ["The vaccine helped eradicate the disease.", "We aim to eradicate hunger in the region."],
  evaluate: ["The teacher evaluates each essay.", "We need to evaluate the risks first."],
  evoke: ["The smell of bread evokes my childhood.", "The film evokes strong emotions."],
  exaggerate: ["He tends to exaggerate his achievements.", "Don't exaggerate; it wasn't that bad."],
  exclude: ["The price excludes breakfast.", "They were excluded from the meeting."],
  exemplify: ["Her career exemplifies hard work.", "This building exemplifies modern design."],
  exhaust: ["The long hike exhausted everyone.", "We exhausted our supplies by noon."],
  exploit: ["Some companies exploit cheap labor.", "She exploited every chance to learn."],
  extensive: ["The fire caused extensive damage.", "He has extensive knowledge of history."],
  fabricate: ["He fabricated an excuse for being late.", "The parts are fabricated from steel."],
  facilitate: ["A good map facilitates travel.", "The teacher facilitated the discussion."],
  fluctuate: ["Temperatures fluctuate throughout the day.", "Stock prices fluctuate constantly."],
  formidable: ["She is a formidable opponent.", "They faced a formidable challenge."],
  foster: ["The program fosters teamwork.", "They decided to foster a child."],
  fragile: ["The package is marked 'fragile'.", "Their peace agreement is still fragile."],
  generate: ["The dam generates electricity.", "The ad generated a lot of interest."],
  gratitude: ["She expressed her gratitude with a gift.", "He felt deep gratitude toward his teachers."],
  hypothesis: ["The experiment supports the hypothesis.", "Her hypothesis turned out to be correct."],
  ideology: ["The two parties have opposing ideologies.", "His ideology shaped his decisions."],
  illustrate: ["This example illustrates the problem.", "She illustrated the book with drawings."],
  imminent: ["The workers sensed an imminent layoff.", "A decision is imminent."],
  impartial: ["A referee must remain impartial.", "We need an impartial review of the case."],
  implement: ["The school implemented a new policy.", "It took months to implement the changes."],
  implication: ["Consider the implications of the law.", "His remark had serious implications."],
  imply: ["His tone implied disappointment.", "I didn't mean to imply that you were wrong."],
  inadequate: ["The lighting was inadequate for reading.", "Their response was completely inadequate."],
  incentive: ["Tax breaks are an incentive to invest.", "There's little incentive to change."],
  incline: ["I incline toward the cheaper option.", "She felt inclined to say no."],
  incorporate: ["We incorporated your feedback into the design.", "The recipe incorporates local spices."],
  indispensable: ["She has become indispensable to the team.", "Clean water is indispensable to health."],
  infer: ["From her smile, I inferred good news.", "Readers must infer the meaning."],
  initiate: ["The company initiated a recall.", "He initiated the conversation."],
  innovative: ["They use an innovative teaching method.", "The phone has several innovative features."],
  integrity: ["No one doubts her integrity.", "Engineers checked the bridge's structural integrity."],
  intricate: ["The watch has an intricate mechanism.", "She wove an intricate pattern."],
  intrinsic: ["Learning has intrinsic value.", "Risk is intrinsic to any investment."],
  intuition: ["Her intuition told her to wait.", "Good designers trust their intuition."],
  justify: ["Nothing can justify such cruelty.", "He couldn't justify the extra cost."],
  legitimate: ["She has a legitimate claim to the land.", "Is this a legitimate business?"],
  leverage: ["They used their size to leverage better deals.", "She leveraged her network to find a job."],
  lucrative: ["He left for a more lucrative job.", "Tourism is a lucrative industry here."],
  magnitude: ["No one grasped the magnitude of the disaster.", "An earthquake of magnitude 7 struck."],
  meticulous: ["He kept meticulous records.", "Her meticulous planning paid off."],
  notion: ["She rejected the notion entirely.", "I have a vague notion of how it works."],
  nurture: ["Parents nurture their children's talents.", "The soil nurtures the young plants."],
  objective: ["Our main objective is customer safety.", "Try to stay objective when judging."],
  obsolete: ["Floppy disks are now obsolete.", "New software made the device obsolete."],
  ominous: ["There was an ominous silence.", "Dark, ominous clouds gathered."],
  paramount: ["Customer trust is of paramount importance.", "Safety is paramount on the site."],
  peculiar: ["The milk had a peculiar taste.", "She has a peculiar way of laughing."],
  perceive: ["He perceived a change in her mood.", "Colors are perceived differently by people."],
  perpetual: ["The mountains have perpetual snow.", "She seems to live in perpetual motion."],
  persistent: ["A persistent cough kept him awake.", "Her persistent efforts finally succeeded."],
  precede: ["A short film preceded the movie.", "The years that precede retirement are busy."],
  predominant: ["Green is the predominant color here.", "Farming is the predominant occupation."],
  preliminary: ["The preliminary results look promising.", "After a preliminary check, all seemed fine."],
  prevail: ["Common sense will prevail.", "Calm prevailed after the storm."],
  prohibit: ["The rules prohibit running by the pool.", "The law prohibits selling alcohol to minors."],
  prone: ["The area is prone to flooding.", "He is prone to forgetting names."],
  prospective: ["Prospective buyers toured the house.", "She interviewed a prospective employee."],
  provoke: ["His comments provoked an argument.", "The decision provoked widespread anger."],
  prudent: ["It would be prudent to wait.", "A prudent investor spreads the risk."],
  rational: ["There must be a rational explanation.", "Stay rational and weigh the facts."],
  reconcile: ["It's hard to reconcile the two accounts.", "The friends finally reconciled."],
  redundant: ["The phrase is redundant; cut it.", "Hundreds of workers were made redundant."],
  refute: ["The lawyer refuted every accusation.", "New data refuted the old theory."],
  reinforce: ["Steel bars reinforce the concrete.", "The trip reinforced our friendship."],
  remarkable: ["She has a remarkable memory.", "It was a remarkable recovery."],
  render: ["The shock rendered her speechless.", "The software renders 3D images quickly."],
  resolve: ["They resolved the dispute peacefully.", "She resolved to exercise every day."],
  retain: ["Plants retain water in their leaves.", "He retained his title for a third year."],
  retrieve: ["The dog retrieved the ball.", "I retrieved the file from the backup."],
  robust: ["The car has a robust engine.", "We need a more robust security system."],
  scrutiny: ["The deal came under close scrutiny.", "Her work withstood careful scrutiny."],
  simultaneous: ["The two events were simultaneous.", "Simultaneous translation was provided."],
  skeptical: ["She remained skeptical of his promises.", "Investors are skeptical about the plan."],
  sophisticated: ["The lab uses sophisticated equipment.", "She has sophisticated taste in art."],
  spontaneous: ["They took a spontaneous trip to the coast.", "The crowd broke into spontaneous applause."],
  stagnant: ["The pond water was stagnant.", "Sales have been stagnant for months."],
  supplement: ["She takes an iron supplement daily.", "He supplements his income with freelance work."],
  suppress: ["The government tried to suppress the news.", "She struggled to suppress a laugh."],
  susceptible: ["Young plants are susceptible to frost.", "He is susceptible to flattery."],
  tangible: ["There are no tangible benefits yet.", "Her relief was almost tangible."],
  tentative: ["We have a tentative agreement.", "She took a tentative step forward."],
  transparent: ["The company aims to be transparent.", "The water was clear and transparent."],
  ubiquitous: ["Coffee shops are now ubiquitous.", "Plastic is ubiquitous in modern life."],
  unanimous: ["The decision was unanimous.", "They were unanimous in their praise."],
  underlying: ["The doctor found the underlying cause.", "There are underlying tensions in the group."],
  undertake: ["She undertook the difficult task alone.", "They will undertake a full review."],
  coincidence: ["By sheer coincidence, we wore the same shirt.", "It was no coincidence that prices rose."],
  diplomatic: ["She gave a diplomatic reply.", "He handled the dispute in a diplomatic way."],
  discern: ["I could barely discern the shape in the fog.", "It's hard to discern his true intentions."],
  elicit: ["The teacher's question elicited no response.", "The ad aims to elicit an emotional reaction."],
  inquiry: ["We received an inquiry about the job.", "The police opened an inquiry into the crash."],
  compelling: ["She made a compelling argument.", "The novel tells a compelling story."],
  advocacy: ["Her advocacy helped change the law.", "The group is known for its advocacy of human rights."],
  comprehend: ["He couldn't comprehend the instructions.", "It's hard to comprehend such kindness."],
  conscientious: ["She is a conscientious student.", "He is conscientious about recycling."]
};
