// Extra example sentences (memory by context). Maps a headword -> array of
// ADDITIONAL English-only sentences. Combined with the word's own `example`
// (in words.js), the card can show several sentences in different contexts
// BEFORE the learner flips to see the Thai meaning.
//
// Kept separate so coverage can grow without touching the main word list.
// Words not listed here still show their single `example` from words.js.
const EXAMPLES = {
  // ---- ขั้นสูง (Advanced) ----
  abundant: ["The garden produced an abundant harvest this year.", "Fresh water is abundant in this region."],
  accomplish: ["She accomplished more in a week than most do in a month.", "With teamwork, we can accomplish almost anything."],
  acknowledge: ["The company acknowledged the error and apologized.", "He nodded to acknowledge her presence."],
  acquire: ["Over time, he acquired a taste for spicy food.", "The museum acquired a rare painting."],
  adequate: ["The salary is adequate for a single person.", "Make sure you get adequate rest before the trip."],
  ambiguous: ["The contract's wording was dangerously ambiguous.", "Her smile was ambiguous — I couldn't read it."],
  anticipate: ["We anticipate heavy traffic during the holidays.", "A good player anticipates the opponent's moves."],
  arbitrary: ["The rule seemed arbitrary and unfair.", "They picked the winner in an arbitrary way."],
  assess: ["The doctor assessed the patient's condition.", "Let's assess the damage before deciding."],
  assume: ["Never assume people know what you mean.", "I assumed the meeting was canceled."],
  authentic: ["The restaurant serves authentic Italian food.", "Experts confirmed the painting was authentic."],
  bias: ["The judge showed no bias toward either side.", "We must remove bias from the hiring process."],
  cease: ["The factory ceased production last year.", "The rain finally ceased at noon."],
  coherent: ["After some sleep, his thoughts became coherent.", "She presented a coherent plan to the board."],
  collaborate: ["Designers and engineers collaborate on every product.", "The two authors collaborated on a novel."],
  compel: ["The evidence compelled them to change their minds.", "Nothing can compel me to lie."],
  competent: ["She is a highly competent surgeon.", "You need a competent lawyer for this case."],
  comprehensive: ["The book is a comprehensive guide to gardening.", "We need a comprehensive review of the system."],
  consequence: ["He didn't think about the consequences of his actions.", "As a consequence, the project was delayed."],
  consistent: ["Her grades have been consistent all year.", "A consistent routine improves sleep."],
  contemplate: ["He sat by the lake, contemplating his future.", "We're contemplating a move to another city."],
  controversial: ["The new law is highly controversial.", "She made a controversial decision."],
  convey: ["The teacher used images to convey the idea.", "Please convey my thanks to your team."],
  crucial: ["The next few days are crucial for the campaign.", "Sleep is crucial to recovery."],
  deliberate: ["It was a deliberate attempt to mislead us.", "She spoke in a slow, deliberate voice."],
  demonstrate: ["The study demonstrates a clear link.", "Let me demonstrate the correct technique."],
  deteriorate: ["His eyesight deteriorated with age.", "Relations between the two sides deteriorated."],
  diligent: ["A diligent worker checks every detail.", "Her diligent research paid off."],
  diminish: ["The pain gradually diminished.", "Nothing could diminish her enthusiasm."],
  distinct: ["There are three distinct stages to the process.", "The two brothers have distinct personalities."],
  diverse: ["The city has a diverse population.", "We offer a diverse range of products."],
  dubious: ["He made a dubious claim about his past.", "I'm dubious about the benefits of the diet."],
  eligible: ["Only members are eligible for the discount.", "She is eligible to vote this year."],
  emerge: ["A new leader emerged from the crisis.", "The sun emerged from behind the clouds."],
  enhance: ["Good lighting enhances the photo.", "The update enhances the app's speed."],
  evident: ["It was evident that she had been crying.", "His talent is evident in every painting."],
  exceed: ["The results exceeded all expectations.", "Don't exceed the speed limit."],
  explicit: ["He gave explicit instructions.", "The map shows the route in explicit detail."],
  feasible: ["Is it feasible to finish by Friday?", "They studied whether the plan was feasible."],
  fundamental: ["Honesty is fundamental to trust.", "There's a fundamental flaw in the design."],
  genuine: ["She showed genuine interest in the topic.", "Is this a genuine leather bag?"],
  hinder: ["Heavy snow hindered the rescue effort.", "Don't let fear hinder your progress."],
  impose: ["The city imposed a curfew.", "I don't want to impose on your time."],
  inevitable: ["With such effort, success was inevitable.", "Aging is an inevitable part of life."],
  inherent: ["There are inherent dangers in the sport.", "Curiosity is inherent in children."],
  mitigate: ["Planting trees can mitigate flooding.", "We took steps to mitigate the risk."],
  notorious: ["The road is notorious for accidents.", "He's notorious for arriving late."],
  optimal: ["Find the optimal route to save fuel.", "Water the plants at the optimal time."],
  plausible: ["She gave a plausible excuse.", "It's a plausible theory, but unproven."],
  pragmatic: ["We need a pragmatic solution, not a perfect one.", "She took a pragmatic approach to the budget."],
  profound: ["The book had a profound effect on me.", "He spoke with profound sadness."],
  prominent: ["She's a prominent figure in science.", "The sign was placed in a prominent spot."],
  reluctant: ["He was reluctant to admit his mistake.", "She gave a reluctant nod."],
  resilient: ["The economy proved surprisingly resilient.", "Children are remarkably resilient."],
  rigorous: ["The product passed rigorous testing.", "She follows a rigorous training schedule."],
  subtle: ["There's a subtle hint of lemon in the sauce.", "He made a subtle change to the design."],
  sufficient: ["We have sufficient evidence to proceed.", "One example is not sufficient."],
  sustain: ["The bridge can sustain heavy loads.", "It's hard to sustain that pace."],
  tedious: ["Filling out forms is tedious work.", "The lecture was long and tedious."],
  thorough: ["She gave the room a thorough cleaning.", "We need a thorough investigation."],
  trivial: ["Don't argue over trivial details.", "The cost is trivial compared to the benefit."],
  versatile: ["A smartphone is a versatile tool.", "She's a versatile player who can fill any role."],
  viable: ["Solar power is now a viable option.", "Is the business model viable?"],
  vivid: ["She has vivid memories of childhood.", "The sunset was a vivid orange."],
  vulnerable: ["The elderly are vulnerable to the cold.", "He felt vulnerable after the loss."],

  // ---- ธุรกิจ (Business) ----
  invoice: ["We'll issue the invoice once the work is done.", "The invoice is due within 30 days."],
  quotation: ["Could you send a quotation for 500 units?", "The quotation does not include shipping."],
  budget: ["The marketing budget was cut this year.", "We finished the project under budget."],
  revenue: ["Online sales boosted our revenue.", "Revenue fell sharply last quarter."],
  profit: ["The store made a small profit last month.", "They sold the company for a huge profit."],
  refund: ["You can get a full refund within 14 days.", "They refused to give me a refund."],
  overdue: ["The payment is now overdue.", "The library book is two days overdue."],
  supplier: ["We switched to a cheaper supplier.", "Our main supplier is overseas."],
  "on behalf of": ["I'm signing on behalf of the director.", "She accepted the award on behalf of the team."],

  // ---- ระดับกลาง (Intermediate) ----
  afford: ["We can't afford to make mistakes.", "Can you afford the rent on your own?"],
  avoid: ["Avoid the highway during rush hour.", "She avoided eye contact."],
  improve: ["His English improved quickly.", "We're always looking to improve."],
  suggest: ["I suggest we take a break.", "The data suggests a different conclusion."],
  depend: ["It depends on what you want.", "Many families depend on this factory."]
};
