// Synonym lookup for memory aid: maps an English headword -> simpler/related
// English synonyms. Shown as a hint on the card so learners can connect a hard
// word to easier words they already know.
//
// Kept separate from words.js so synonyms can be extended without touching the
// main vocabulary array. Words not listed here simply show no hint.
const SYNONYMS = {
  // ----- ระดับกลาง (Intermediate) -----
  appointment: "meeting, booking",
  schedule: "timetable, plan",
  remind: "prompt, jog the memory",
  borrow: "take on loan, use temporarily",
  lend: "loan, give temporarily",
  afford: "pay for, manage",
  complain: "grumble, protest",
  apologize: "say sorry, express regret",
  decide: "choose, determine",
  suggest: "propose, recommend",
  explain: "clarify, describe",
  realize: "understand, become aware",
  prepare: "get ready, arrange",
  avoid: "evade, steer clear of",
  manage: "handle, run",
  available: "free, accessible",
  convenient: "handy, suitable",
  comfortable: "cozy, relaxed",
  similar: "alike, comparable",
  necessary: "needed, essential",
  enough: "sufficient, adequate",
  almost: "nearly, about",
  actually: "in fact, really",
  instead: "rather, alternatively",
  although: "though, even if",
  however: "but, nevertheless",
  increase: "rise, grow",
  reduce: "decrease, lower",
  improve: "better, enhance",
  depend: "rely, count on",

  // ----- ขั้นสูง (Advanced) -----
  abundant: "plentiful, ample",
  accomplish: "achieve, complete",
  accurate: "correct, precise",
  acknowledge: "admit, recognize",
  acquire: "obtain, get",
  adequate: "enough, sufficient",
  advocate: "support, promote",
  aesthetic: "artistic, visual",
  allocate: "assign, distribute",
  ambiguous: "unclear, vague",
  analyze: "examine, study",
  anticipate: "expect, foresee",
  apparent: "obvious, clear",
  arbitrary: "random, unreasonable",
  articulate: "well-spoken, clear",
  aspire: "aim, hope",
  assess: "evaluate, judge",
  assume: "suppose, presume",
  attain: "achieve, reach",
  authentic: "genuine, real",
  benevolent: "kind, generous",
  bias: "prejudice, partiality",
  boost: "increase, raise",
  brilliant: "clever, outstanding",
  candid: "honest, frank",
  capacity: "ability, volume",
  cease: "stop, halt",
  coherent: "logical, clear",
  coincide: "match, align",
  collaborate: "cooperate, work together",
  commence: "begin, start",
  compel: "force, oblige",
  compensate: "repay, make up for",
  competent: "capable, skilled",
  comprehensive: "complete, thorough",
  compromise: "middle ground, settlement",
  conceive: "imagine, devise",
  concise: "brief, short",
  condemn: "criticize, denounce",
  conform: "comply, follow",
  consensus: "agreement, accord",
  consequence: "result, outcome",
  conserve: "save, protect",
  considerable: "significant, large",
  consistent: "steady, reliable",
  conspicuous: "noticeable, obvious",
  constitute: "form, make up",
  contemplate: "consider, ponder",
  contradict: "oppose, conflict with",
  controversial: "debatable, divisive",
  convey: "communicate, express",
  cope: "manage, deal with",
  crucial: "essential, vital",
  cumulative: "accumulating, growing",
  curb: "restrain, limit",
  deduce: "infer, conclude",
  deficient: "lacking, insufficient",
  deliberate: "intentional, planned",
  demonstrate: "show, prove",
  denote: "indicate, signify",
  deteriorate: "worsen, decline",
  devise: "invent, plan",
  diligent: "hardworking, industrious",
  diminish: "decrease, reduce",
  discrepancy: "difference, inconsistency",
  distinct: "separate, clear",
  diverse: "varied, different",
  dominant: "leading, controlling",
  dubious: "doubtful, questionable",
  eligible: "qualified, entitled",
  eloquent: "articulate, expressive",
  elaborate: "detailed, expand on",
  embrace: "accept, welcome",
  emerge: "appear, arise",
  eminent: "famous, distinguished",
  empirical: "observed, factual",
  endeavor: "attempt, effort",
  endorse: "approve, support",
  enhance: "improve, boost",
  enormous: "huge, massive",
  entitle: "authorize, allow",
  equivalent: "equal, the same",
  eradicate: "eliminate, wipe out",
  evaluate: "assess, judge",
  evident: "clear, obvious",
  evoke: "bring out, summon",
  exaggerate: "overstate, magnify",
  exceed: "surpass, go beyond",
  exclude: "leave out, omit",
  exemplify: "illustrate, represent",
  exhaust: "tire out, use up",
  explicit: "clear, direct",
  exploit: "use, take advantage of",
  extensive: "wide, broad",
  fabricate: "invent, make up",
  facilitate: "ease, help",
  feasible: "possible, achievable",
  fluctuate: "vary, change",
  formidable: "powerful, daunting",
  foster: "encourage, promote",
  fragile: "delicate, breakable",
  fundamental: "basic, essential",
  generate: "produce, create",
  genuine: "real, authentic",
  gratitude: "thankfulness, appreciation",
  hinder: "obstruct, block",
  hypothesis: "theory, assumption",
  ideology: "belief system, doctrine",
  illustrate: "show, demonstrate",
  imminent: "approaching, near",
  impartial: "unbiased, neutral",
  implement: "carry out, apply",
  implication: "consequence, suggestion",
  imply: "suggest, hint",
  impose: "enforce, force",
  inadequate: "insufficient, lacking",
  incentive: "motivation, reward",
  incline: "tend, lean",
  incorporate: "include, combine",
  indispensable: "essential, vital",
  inevitable: "unavoidable, certain",
  infer: "deduce, conclude",
  inherent: "built-in, natural",
  initiate: "begin, start",
  innovative: "creative, original",
  integrity: "honesty, uprightness",
  intricate: "complex, complicated",
  intrinsic: "inherent, essential",
  intuition: "instinct, gut feeling",
  justify: "defend, explain",
  legitimate: "legal, valid",
  leverage: "use, exploit",
  lucrative: "profitable, rewarding",
  magnitude: "size, importance",
  meticulous: "careful, precise",
  mitigate: "reduce, ease",
  notion: "idea, concept",
  notorious: "infamous, ill-famed",
  nurture: "nourish, cultivate",
  objective: "goal, unbiased",
  obsolete: "outdated, old-fashioned",
  ominous: "threatening, foreboding",
  optimal: "best, ideal",
  paramount: "supreme, foremost",
  peculiar: "strange, odd",
  perceive: "notice, sense",
  perpetual: "constant, endless",
  persistent: "determined, continuous",
  plausible: "believable, credible",
  pragmatic: "practical, realistic",
  precede: "come before, lead",
  predominant: "main, prevailing",
  preliminary: "initial, introductory",
  prevail: "triumph, dominate",
  profound: "deep, intense",
  prohibit: "forbid, ban",
  prominent: "notable, well-known",
  prone: "likely, inclined",
  prospective: "potential, future",
  provoke: "incite, trigger",
  prudent: "cautious, wise",
  rational: "logical, sensible",
  reconcile: "settle, make peace",
  redundant: "unnecessary, excessive",
  refute: "disprove, deny",
  reinforce: "strengthen, support",
  reluctant: "unwilling, hesitant",
  remarkable: "extraordinary, impressive",
  render: "make, provide",
  resilient: "tough, adaptable",
  resolve: "settle, determine",
  retain: "keep, hold",
  retrieve: "recover, get back",
  rigorous: "strict, demanding",
  robust: "strong, sturdy",
  scrutiny: "examination, inspection",
  simultaneous: "concurrent, at the same time",
  skeptical: "doubtful, unconvinced",
  sophisticated: "advanced, refined",
  spontaneous: "impulsive, unplanned",
  stagnant: "still, inactive",
  subtle: "faint, delicate",
  sufficient: "enough, adequate",
  supplement: "addition, add to",
  suppress: "restrain, hold back",
  susceptible: "vulnerable, prone",
  sustain: "maintain, support",
  tangible: "concrete, touchable",
  tedious: "boring, dull",
  tentative: "provisional, uncertain",
  thorough: "complete, detailed",
  transparent: "clear, see-through",
  trivial: "minor, unimportant",
  ubiquitous: "everywhere, widespread",
  unanimous: "in full agreement, united",
  underlying: "basic, hidden",
  undertake: "take on, attempt",
  versatile: "adaptable, all-around",
  viable: "workable, feasible",
  vivid: "bright, clear",
  coincidence: "chance, accident",
  diplomatic: "tactful, sensitive",
  discern: "detect, distinguish",
  elicit: "draw out, evoke",
  inquiry: "question, investigation",
  compelling: "convincing, persuasive",
  advocacy: "support, campaigning",
  comprehend: "understand, grasp",
  conscientious: "careful, responsible",
  vulnerable: "exposed, defenseless"
};
