// Starter vocabulary for the flashcard app.
// Each entry: { en, th, pos, example, category }
// pos = part of speech (optional), example = English example sentence (optional)
//
// The "ชีวิตประจำวัน" (Everyday) category is intentionally the largest — it is the
// app's main focus and the default category shown on load (see js/app.js).
const STARTER_WORDS = [
  // ===== ชีวิตประจำวัน (Everyday) — คำที่ใช้บ่อยที่สุดในแต่ละวัน =====

  // กิจวัตรประจำวัน (Daily routine verbs)
  { en: "wake up", th: "ตื่นนอน", pos: "v.", example: "I wake up at 6 a.m. every day.", category: "ชีวิตประจำวัน" },
  { en: "sleep", th: "นอนหลับ", pos: "v.", example: "I usually sleep eight hours.", category: "ชีวิตประจำวัน" },
  { en: "eat", th: "กิน", pos: "v.", example: "Let's eat dinner together.", category: "ชีวิตประจำวัน" },
  { en: "drink", th: "ดื่ม", pos: "v.", example: "I drink water every morning.", category: "ชีวิตประจำวัน" },
  { en: "wash", th: "ล้าง / ซัก", pos: "v.", example: "Please wash your hands.", category: "ชีวิตประจำวัน" },
  { en: "brush", th: "แปรง (ฟัน/ผม)", pos: "v.", example: "I brush my teeth twice a day.", category: "ชีวิตประจำวัน" },
  { en: "cook", th: "ทำอาหาร", pos: "v.", example: "She likes to cook on weekends.", category: "ชีวิตประจำวัน" },
  { en: "clean", th: "สะอาด / ทำความสะอาด", pos: "adj./v.", example: "Please keep the room clean.", category: "ชีวิตประจำวัน" },
  { en: "buy", th: "ซื้อ", pos: "v.", example: "I want to buy a new phone.", category: "ชีวิตประจำวัน" },
  { en: "pay", th: "จ่ายเงิน", pos: "v.", example: "Can I pay by card?", category: "ชีวิตประจำวัน" },
  { en: "walk", th: "เดิน", pos: "v.", example: "I walk to the office every day.", category: "ชีวิตประจำวัน" },
  { en: "drive", th: "ขับรถ", pos: "v.", example: "She drives to work.", category: "ชีวิตประจำวัน" },
  { en: "wait", th: "รอ", pos: "v.", example: "Please wait a moment.", category: "ชีวิตประจำวัน" },
  { en: "rest", th: "พักผ่อน", pos: "v./n.", example: "You should rest when you are sick.", category: "ชีวิตประจำวัน" },

  // เวลา (Time)
  { en: "morning", th: "ตอนเช้า", pos: "n.", example: "I drink coffee every morning.", category: "ชีวิตประจำวัน" },
  { en: "afternoon", th: "ตอนบ่าย", pos: "n.", example: "We have a class in the afternoon.", category: "ชีวิตประจำวัน" },
  { en: "evening", th: "ตอนเย็น", pos: "n.", example: "I relax in the evening.", category: "ชีวิตประจำวัน" },
  { en: "night", th: "กลางคืน", pos: "n.", example: "It gets cold at night.", category: "ชีวิตประจำวัน" },
  { en: "today", th: "วันนี้", pos: "adv.", example: "What are you doing today?", category: "ชีวิตประจำวัน" },
  { en: "tomorrow", th: "พรุ่งนี้", pos: "adv.", example: "See you tomorrow.", category: "ชีวิตประจำวัน" },
  { en: "yesterday", th: "เมื่อวาน", pos: "adv.", example: "I was busy yesterday.", category: "ชีวิตประจำวัน" },
  { en: "early", th: "เช้า / แต่เนิ่น ๆ", pos: "adj./adv.", example: "I woke up early today.", category: "ชีวิตประจำวัน" },
  { en: "late", th: "สาย / ดึก", pos: "adj./adv.", example: "Sorry, I am late.", category: "ชีวิตประจำวัน" },

  // บ้านและของใช้ (Home & things)
  { en: "house", th: "บ้าน", pos: "n.", example: "Their house is near the river.", category: "ชีวิตประจำวัน" },
  { en: "room", th: "ห้อง", pos: "n.", example: "My room is small but tidy.", category: "ชีวิตประจำวัน" },
  { en: "door", th: "ประตู", pos: "n.", example: "Please close the door.", category: "ชีวิตประจำวัน" },
  { en: "key", th: "กุญแจ", pos: "n.", example: "I can't find my key.", category: "ชีวิตประจำวัน" },
  { en: "phone", th: "โทรศัพท์", pos: "n.", example: "My phone battery is low.", category: "ชีวิตประจำวัน" },
  { en: "clothes", th: "เสื้อผ้า", pos: "n.", example: "I need to wash my clothes.", category: "ชีวิตประจำวัน" },
  { en: "bag", th: "กระเป๋า", pos: "n.", example: "I left my bag at home.", category: "ชีวิตประจำวัน" },
  { en: "money", th: "เงิน", pos: "n.", example: "He saves his money carefully.", category: "ชีวิตประจำวัน" },

  // คน & การพบปะ (People & social)
  { en: "friend", th: "เพื่อน", pos: "n.", example: "She is my best friend.", category: "ชีวิตประจำวัน" },
  { en: "family", th: "ครอบครัว", pos: "n.", example: "I live with my family.", category: "ชีวิตประจำวัน" },
  { en: "neighbor", th: "เพื่อนบ้าน", pos: "n.", example: "My neighbor is very kind.", category: "ชีวิตประจำวัน" },
  { en: "help", th: "ช่วยเหลือ", pos: "v./n.", example: "Can you help me, please?", category: "ชีวิตประจำวัน" },
  { en: "talk", th: "พูดคุย", pos: "v.", example: "Let's talk later.", category: "ชีวิตประจำวัน" },
  { en: "meet", th: "พบ / เจอ", pos: "v.", example: "Nice to meet you.", category: "ชีวิตประจำวัน" },

  // คำที่ใช้บ่อย (Common adjectives)
  { en: "busy", th: "ยุ่ง", pos: "adj.", example: "I am very busy today.", category: "ชีวิตประจำวัน" },
  { en: "free", th: "ว่าง / ฟรี", pos: "adj.", example: "Are you free this evening?", category: "ชีวิตประจำวัน" },
  { en: "easy", th: "ง่าย", pos: "adj.", example: "This game is very easy.", category: "ชีวิตประจำวัน" },
  { en: "difficult", th: "ยาก", pos: "adj.", example: "The exam was difficult.", category: "ชีวิตประจำวัน" },
  { en: "cheap", th: "ถูก (ราคา)", pos: "adj.", example: "This shirt is cheap.", category: "ชีวิตประจำวัน" },
  { en: "expensive", th: "แพง", pos: "adj.", example: "That car is too expensive.", category: "ชีวิตประจำวัน" },
  { en: "near", th: "ใกล้", pos: "adj./prep.", example: "The shop is near my house.", category: "ชีวิตประจำวัน" },
  { en: "far", th: "ไกล", pos: "adj./adv.", example: "The station is far from here.", category: "ชีวิตประจำวัน" },

  // ===== ชีวิตประจำวัน — ระดับกลาง (Everyday · Intermediate) =====
  // คำที่เจอบ่อยในชีวิตจริงแต่ยากขึ้นอีกนิด เหมาะกับคนที่ผ่านชุดพื้นฐานแล้ว
  { en: "appointment", th: "การนัดหมาย", pos: "n.", example: "I have a doctor's appointment at 3.", category: "ระดับกลาง" },
  { en: "schedule", th: "ตารางเวลา / กำหนดการ", pos: "n./v.", example: "Let's schedule a call for Monday.", category: "ระดับกลาง" },
  { en: "remind", th: "เตือนความจำ", pos: "v.", example: "Please remind me to call her.", category: "ระดับกลาง" },
  { en: "borrow", th: "ยืม", pos: "v.", example: "Can I borrow your pen?", category: "ระดับกลาง" },
  { en: "lend", th: "ให้ยืม", pos: "v.", example: "She lent me some money.", category: "ระดับกลาง" },
  { en: "afford", th: "มีเงินพอจ่าย", pos: "v.", example: "I can't afford a new car right now.", category: "ระดับกลาง" },
  { en: "complain", th: "บ่น / ร้องเรียน", pos: "v.", example: "He always complains about the weather.", category: "ระดับกลาง" },
  { en: "apologize", th: "ขอโทษ", pos: "v.", example: "I apologize for being late.", category: "ระดับกลาง" },
  { en: "decide", th: "ตัดสินใจ", pos: "v.", example: "We need to decide soon.", category: "ระดับกลาง" },
  { en: "suggest", th: "แนะนำ / เสนอ", pos: "v.", example: "Can you suggest a good restaurant?", category: "ระดับกลาง" },
  { en: "explain", th: "อธิบาย", pos: "v.", example: "Let me explain the plan.", category: "ระดับกลาง" },
  { en: "realize", th: "ตระหนัก / เพิ่งรู้ตัว", pos: "v.", example: "I didn't realize it was so late.", category: "ระดับกลาง" },
  { en: "prepare", th: "เตรียมตัว", pos: "v.", example: "I need to prepare for the exam.", category: "ระดับกลาง" },
  { en: "avoid", th: "หลีกเลี่ยง", pos: "v.", example: "Try to avoid traffic in the morning.", category: "ระดับกลาง" },
  { en: "manage", th: "จัดการ / รับมือ", pos: "v.", example: "She manages her time well.", category: "ระดับกลาง" },
  { en: "available", th: "ว่าง / พร้อมใช้งาน", pos: "adj.", example: "Are you available tomorrow?", category: "ระดับกลาง" },
  { en: "convenient", th: "สะดวก", pos: "adj.", example: "Is this time convenient for you?", category: "ระดับกลาง" },
  { en: "comfortable", th: "สบาย", pos: "adj.", example: "This chair is very comfortable.", category: "ระดับกลาง" },
  { en: "similar", th: "คล้ายกัน", pos: "adj.", example: "Our ideas are quite similar.", category: "ระดับกลาง" },
  { en: "necessary", th: "จำเป็น", pos: "adj.", example: "Sleep is necessary for health.", category: "ระดับกลาง" },
  { en: "enough", th: "เพียงพอ", pos: "adj./adv.", example: "Do we have enough time?", category: "ระดับกลาง" },
  { en: "almost", th: "เกือบ", pos: "adv.", example: "I'm almost finished.", category: "ระดับกลาง" },
  { en: "actually", th: "จริง ๆ แล้ว", pos: "adv.", example: "Actually, I changed my mind.", category: "ระดับกลาง" },
  { en: "instead", th: "แทนที่จะ", pos: "adv.", example: "Let's stay home instead.", category: "ระดับกลาง" },
  { en: "although", th: "ถึงแม้ว่า", pos: "conj.", example: "Although it rained, we had fun.", category: "ระดับกลาง" },
  { en: "however", th: "อย่างไรก็ตาม", pos: "adv.", example: "It's expensive; however, it's worth it.", category: "ระดับกลาง" },
  { en: "increase", th: "เพิ่มขึ้น", pos: "v.", example: "Prices increase every year.", category: "ระดับกลาง" },
  { en: "reduce", th: "ลดลง", pos: "v.", example: "We should reduce plastic waste.", category: "ระดับกลาง" },
  { en: "improve", th: "ทำให้ดีขึ้น", pos: "v.", example: "Reading helps improve your vocabulary.", category: "ระดับกลาง" },
  { en: "depend", th: "ขึ้นอยู่กับ", pos: "v.", example: "It depends on the weather.", category: "ระดับกลาง" },

  // ===== อาหาร (Food) =====
  { en: "rice", th: "ข้าว", pos: "n.", example: "We eat rice with almost every meal.", category: "อาหาร" },
  { en: "water", th: "น้ำ", pos: "n.", example: "Can I have a glass of water?", category: "อาหาร" },
  { en: "delicious", th: "อร่อย", pos: "adj.", example: "This soup is delicious.", category: "อาหาร" },
  { en: "hungry", th: "หิว", pos: "adj.", example: "I am hungry, let's eat.", category: "อาหาร" },
  { en: "spicy", th: "เผ็ด", pos: "adj.", example: "Thai food is often spicy.", category: "อาหาร" },
  { en: "vegetable", th: "ผัก", pos: "n.", example: "Eat more vegetables for your health.", category: "อาหาร" },
  { en: "sweet", th: "หวาน", pos: "adj.", example: "The mango is very sweet.", category: "อาหาร" },
  { en: "breakfast", th: "อาหารเช้า", pos: "n.", example: "Breakfast is my favorite meal.", category: "อาหาร" },

  // ===== การเดินทาง (Travel) =====
  { en: "airport", th: "สนามบิน", pos: "n.", example: "We arrived at the airport early.", category: "การเดินทาง" },
  { en: "ticket", th: "ตั๋ว", pos: "n.", example: "I bought a train ticket.", category: "การเดินทาง" },
  { en: "map", th: "แผนที่", pos: "n.", example: "Let me check the map.", category: "การเดินทาง" },
  { en: "luggage", th: "กระเป๋าเดินทาง / สัมภาระ", pos: "n.", example: "My luggage is very heavy.", category: "การเดินทาง" },
  { en: "hotel", th: "โรงแรม", pos: "n.", example: "The hotel is near the beach.", category: "การเดินทาง" },
  { en: "arrive", th: "มาถึง", pos: "v.", example: "What time does the bus arrive?", category: "การเดินทาง" },
  { en: "abroad", th: "ต่างประเทศ", pos: "adv.", example: "She is studying abroad.", category: "การเดินทาง" },
  { en: "journey", th: "การเดินทาง", pos: "n.", example: "It was a long journey.", category: "การเดินทาง" },

  // ===== อารมณ์/ความรู้สึก (Emotions) =====
  { en: "happy", th: "มีความสุข / ดีใจ", pos: "adj.", example: "I am happy to see you.", category: "อารมณ์" },
  { en: "sad", th: "เศร้า", pos: "adj.", example: "She felt sad about the news.", category: "อารมณ์" },
  { en: "angry", th: "โกรธ", pos: "adj.", example: "Don't be angry with me.", category: "อารมณ์" },
  { en: "tired", th: "เหนื่อย", pos: "adj.", example: "I am tired after work.", category: "อารมณ์" },
  { en: "afraid", th: "กลัว", pos: "adj.", example: "He is afraid of dogs.", category: "อารมณ์" },
  { en: "excited", th: "ตื่นเต้น (ดีใจ)", pos: "adj.", example: "We are excited about the trip.", category: "อารมณ์" },
  { en: "bored", th: "เบื่อ", pos: "adj.", example: "The kids are bored at home.", category: "อารมณ์" },
  { en: "proud", th: "ภูมิใจ", pos: "adj.", example: "I am proud of you.", category: "อารมณ์" },

  // ===== การงาน (Work) =====
  { en: "meeting", th: "การประชุม", pos: "n.", example: "We have a meeting at 9 a.m.", category: "การงาน" },
  { en: "deadline", th: "กำหนดส่งงาน", pos: "n.", example: "The deadline is tomorrow.", category: "การงาน" },
  { en: "salary", th: "เงินเดือน", pos: "n.", example: "He got a higher salary.", category: "การงาน" },
  { en: "manager", th: "ผู้จัดการ", pos: "n.", example: "Ask the manager for help.", category: "การงาน" },
  { en: "improve", th: "ปรับปรุง / พัฒนา", pos: "v.", example: "I want to improve my English.", category: "การงาน" },
  { en: "skill", th: "ทักษะ", pos: "n.", example: "Communication is an important skill.", category: "การงาน" },
  { en: "report", th: "รายงาน", pos: "n./v.", example: "Please send me the report.", category: "การงาน" },
  { en: "experience", th: "ประสบการณ์", pos: "n.", example: "She has years of experience.", category: "การงาน" },

  // ===== ขั้นสูง (Advanced) — คำระดับ B2–C1 สำหรับงานวิชาการ/การทำงาน/บทความ =====
  { en: "abundant", th: "อุดมสมบูรณ์ / มากมาย", pos: "adj.", example: "The region has abundant natural resources.", category: "ขั้นสูง" },
  { en: "accomplish", th: "ทำสำเร็จ / บรรลุ", pos: "v.", example: "She accomplished her goal in one year.", category: "ขั้นสูง" },
  { en: "accurate", th: "ถูกต้อง / แม่นยำ", pos: "adj.", example: "Please give me an accurate measurement.", category: "ขั้นสูง" },
  { en: "acknowledge", th: "ยอมรับ / รับทราบ", pos: "v.", example: "He acknowledged his mistake.", category: "ขั้นสูง" },
  { en: "acquire", th: "ได้มา / เข้าครอบครอง", pos: "v.", example: "The company acquired a smaller firm.", category: "ขั้นสูง" },
  { en: "adequate", th: "เพียงพอ / พอเหมาะ", pos: "adj.", example: "We need adequate funding for the project.", category: "ขั้นสูง" },
  { en: "advocate", th: "สนับสนุน / ผู้สนับสนุน", pos: "v./n.", example: "She advocates for human rights.", category: "ขั้นสูง" },
  { en: "aesthetic", th: "เกี่ยวกับความงาม", pos: "adj.", example: "The building has great aesthetic appeal.", category: "ขั้นสูง" },
  { en: "allocate", th: "จัดสรร / แบ่งสรร", pos: "v.", example: "We allocate a budget for marketing.", category: "ขั้นสูง" },
  { en: "ambiguous", th: "กำกวม / คลุมเครือ", pos: "adj.", example: "His answer was ambiguous.", category: "ขั้นสูง" },
  { en: "analyze", th: "วิเคราะห์", pos: "v.", example: "Scientists analyze the data carefully.", category: "ขั้นสูง" },
  { en: "anticipate", th: "คาดการณ์ / คาดหวัง", pos: "v.", example: "We anticipate strong sales this year.", category: "ขั้นสูง" },
  { en: "apparent", th: "ชัดเจน / เห็นได้ชัด", pos: "adj.", example: "It was apparent that he was tired.", category: "ขั้นสูง" },
  { en: "arbitrary", th: "ตามอำเภอใจ / ไร้หลักเกณฑ์", pos: "adj.", example: "The decision seemed arbitrary.", category: "ขั้นสูง" },
  { en: "articulate", th: "พูดได้ชัดเจน / แสดงออกชัด", pos: "adj./v.", example: "She is a very articulate speaker.", category: "ขั้นสูง" },
  { en: "aspire", th: "ใฝ่ฝัน / มุ่งหวัง", pos: "v.", example: "He aspires to become a doctor.", category: "ขั้นสูง" },
  { en: "assess", th: "ประเมิน", pos: "v.", example: "Teachers assess students' progress.", category: "ขั้นสูง" },
  { en: "assume", th: "สันนิษฐาน / คาดเดา", pos: "v.", example: "Don't assume he agrees.", category: "ขั้นสูง" },
  { en: "attain", th: "บรรลุ / ได้รับ", pos: "v.", example: "She attained a high position.", category: "ขั้นสูง" },
  { en: "authentic", th: "แท้จริง / ของแท้", pos: "adj.", example: "This is an authentic Thai dish.", category: "ขั้นสูง" },
  { en: "benevolent", th: "ใจดี / มีเมตตา", pos: "adj.", example: "A benevolent leader cares for the people.", category: "ขั้นสูง" },
  { en: "bias", th: "อคติ / ความลำเอียง", pos: "n.", example: "The report showed a clear bias.", category: "ขั้นสูง" },
  { en: "boost", th: "กระตุ้น / เพิ่ม", pos: "v./n.", example: "The discount boosted sales.", category: "ขั้นสูง" },
  { en: "brilliant", th: "ฉลาดหลักแหลม / ยอดเยี่ยม", pos: "adj.", example: "She had a brilliant idea.", category: "ขั้นสูง" },
  { en: "candid", th: "ตรงไปตรงมา / เปิดเผย", pos: "adj.", example: "I appreciate your candid feedback.", category: "ขั้นสูง" },
  { en: "capacity", th: "ความจุ / ความสามารถ", pos: "n.", example: "The hall has a capacity of 500.", category: "ขั้นสูง" },
  { en: "cease", th: "หยุด / ยุติ", pos: "v.", example: "The noise finally ceased.", category: "ขั้นสูง" },
  { en: "coherent", th: "เป็นเหตุเป็นผล / ปะติดปะต่อ", pos: "adj.", example: "He gave a coherent explanation.", category: "ขั้นสูง" },
  { en: "coincide", th: "เกิดขึ้นพร้อมกัน / ตรงกัน", pos: "v.", example: "Our holidays coincide this year.", category: "ขั้นสูง" },
  { en: "collaborate", th: "ร่วมมือกัน", pos: "v.", example: "The two teams collaborate closely.", category: "ขั้นสูง" },
  { en: "commence", th: "เริ่มต้น", pos: "v.", example: "The ceremony will commence at noon.", category: "ขั้นสูง" },
  { en: "compel", th: "บังคับ / ทำให้จำต้อง", pos: "v.", example: "Hunger compelled them to act.", category: "ขั้นสูง" },
  { en: "compensate", th: "ชดเชย", pos: "v.", example: "The company compensated the workers.", category: "ขั้นสูง" },
  { en: "competent", th: "มีความสามารถ", pos: "adj.", example: "She is a competent manager.", category: "ขั้นสูง" },
  { en: "comprehensive", th: "ครอบคลุม / ละเอียดถี่ถ้วน", pos: "adj.", example: "We need a comprehensive plan.", category: "ขั้นสูง" },
  { en: "compromise", th: "ประนีประนอม", pos: "n./v.", example: "Both sides reached a compromise.", category: "ขั้นสูง" },
  { en: "conceive", th: "คิดขึ้น / ก่อร่าง", pos: "v.", example: "He conceived a new business idea.", category: "ขั้นสูง" },
  { en: "concise", th: "กระชับ / รัดกุม", pos: "adj.", example: "Keep your answer concise.", category: "ขั้นสูง" },
  { en: "condemn", th: "ประณาม / ตัดสินลงโทษ", pos: "v.", example: "Leaders condemned the violence.", category: "ขั้นสูง" },
  { en: "conform", th: "ทำตาม / ปฏิบัติตาม", pos: "v.", example: "Products must conform to standards.", category: "ขั้นสูง" },
  { en: "consensus", th: "ความเห็นพ้องต้องกัน", pos: "n.", example: "We reached a consensus.", category: "ขั้นสูง" },
  { en: "consequence", th: "ผลที่ตามมา", pos: "n.", example: "Every action has consequences.", category: "ขั้นสูง" },
  { en: "conserve", th: "อนุรักษ์ / สงวน", pos: "v.", example: "We must conserve water.", category: "ขั้นสูง" },
  { en: "considerable", th: "มากมาย / ค่อนข้างมาก", pos: "adj.", example: "It took considerable effort.", category: "ขั้นสูง" },
  { en: "consistent", th: "สม่ำเสมอ / คงเส้นคงวา", pos: "adj.", example: "Be consistent in your practice.", category: "ขั้นสูง" },
  { en: "conspicuous", th: "เด่นชัด / สะดุดตา", pos: "adj.", example: "The error was conspicuous.", category: "ขั้นสูง" },
  { en: "constitute", th: "ประกอบเป็น / ถือเป็น", pos: "v.", example: "These rules constitute the law.", category: "ขั้นสูง" },
  { en: "contemplate", th: "ครุ่นคิด / พิจารณา", pos: "v.", example: "She contemplated her future.", category: "ขั้นสูง" },
  { en: "contradict", th: "ขัดแย้ง / โต้แย้ง", pos: "v.", example: "His words contradict his actions.", category: "ขั้นสูง" },
  { en: "controversial", th: "ที่ก่อให้เกิดข้อโต้แย้ง", pos: "adj.", example: "It is a controversial topic.", category: "ขั้นสูง" },
  { en: "convey", th: "สื่อ / ถ่ายทอด", pos: "v.", example: "Words cannot convey my feelings.", category: "ขั้นสูง" },
  { en: "cope", th: "รับมือ / จัดการ", pos: "v.", example: "She copes well with stress.", category: "ขั้นสูง" },
  { en: "crucial", th: "สำคัญยิ่ง", pos: "adj.", example: "Timing is crucial.", category: "ขั้นสูง" },
  { en: "cumulative", th: "ที่สะสมเพิ่มขึ้น", pos: "adj.", example: "The cumulative effect is huge.", category: "ขั้นสูง" },
  { en: "curb", th: "ควบคุม / ยับยั้ง", pos: "v.", example: "We must curb spending.", category: "ขั้นสูง" },
  { en: "deduce", th: "อนุมาน / สรุป", pos: "v.", example: "He deduced the answer from clues.", category: "ขั้นสูง" },
  { en: "deficient", th: "ขาดแคลน / บกพร่อง", pos: "adj.", example: "The diet is deficient in iron.", category: "ขั้นสูง" },
  { en: "deliberate", th: "จงใจ / โดยตั้งใจ", pos: "adj.", example: "It was a deliberate choice.", category: "ขั้นสูง" },
  { en: "demonstrate", th: "แสดงให้เห็น / สาธิต", pos: "v.", example: "Let me demonstrate how it works.", category: "ขั้นสูง" },
  { en: "denote", th: "บ่งบอก / หมายถึง", pos: "v.", example: "Red often denotes danger.", category: "ขั้นสูง" },
  { en: "deteriorate", th: "เสื่อมลง / ทรุดโทรม", pos: "v.", example: "His health deteriorated quickly.", category: "ขั้นสูง" },
  { en: "devise", th: "คิดค้น / วางแผน", pos: "v.", example: "They devised a clever plan.", category: "ขั้นสูง" },
  { en: "diligent", th: "ขยันหมั่นเพียร", pos: "adj.", example: "She is a diligent student.", category: "ขั้นสูง" },
  { en: "diminish", th: "ลดน้อยลง", pos: "v.", example: "Interest in the topic diminished.", category: "ขั้นสูง" },
  { en: "discrepancy", th: "ความไม่สอดคล้องกัน", pos: "n.", example: "There is a discrepancy in the figures.", category: "ขั้นสูง" },
  { en: "distinct", th: "ชัดเจน / แตกต่างชัด", pos: "adj.", example: "These are two distinct species.", category: "ขั้นสูง" },
  { en: "diverse", th: "หลากหลาย", pos: "adj.", example: "We have a diverse team.", category: "ขั้นสูง" },
  { en: "dominant", th: "ที่มีอิทธิพล / เด่น", pos: "adj.", example: "He has a dominant personality.", category: "ขั้นสูง" },
  { en: "dubious", th: "น่าสงสัย / ไม่แน่ใจ", pos: "adj.", example: "The claim seems dubious.", category: "ขั้นสูง" },
  { en: "eligible", th: "มีคุณสมบัติ / มีสิทธิ์", pos: "adj.", example: "Are you eligible for the loan?", category: "ขั้นสูง" },
  { en: "eloquent", th: "คมคาย / พูดจาไพเราะ", pos: "adj.", example: "She gave an eloquent speech.", category: "ขั้นสูง" },
  { en: "elaborate", th: "ละเอียด / ขยายความ", pos: "adj./v.", example: "Could you elaborate on that?", category: "ขั้นสูง" },
  { en: "embrace", th: "โอบกอด / ยอมรับ", pos: "v.", example: "We embrace new technology.", category: "ขั้นสูง" },
  { en: "emerge", th: "โผล่ออกมา / ปรากฏ", pos: "v.", example: "New problems emerged.", category: "ขั้นสูง" },
  { en: "eminent", th: "มีชื่อเสียง / โดดเด่น", pos: "adj.", example: "He is an eminent scientist.", category: "ขั้นสูง" },
  { en: "empirical", th: "อิงประสบการณ์ / เชิงประจักษ์", pos: "adj.", example: "We need empirical evidence.", category: "ขั้นสูง" },
  { en: "endeavor", th: "ความพยายาม / พยายาม", pos: "n./v.", example: "We will endeavor to help.", category: "ขั้นสูง" },
  { en: "endorse", th: "รับรอง / สนับสนุน", pos: "v.", example: "The star endorsed the product.", category: "ขั้นสูง" },
  { en: "enhance", th: "เสริม / ทำให้ดีขึ้น", pos: "v.", example: "Music can enhance your mood.", category: "ขั้นสูง" },
  { en: "enormous", th: "มหึมา / ใหญ่โต", pos: "adj.", example: "It was an enormous task.", category: "ขั้นสูง" },
  { en: "entitle", th: "ให้สิทธิ์ / ตั้งชื่อเรื่อง", pos: "v.", example: "This ticket entitles you to entry.", category: "ขั้นสูง" },
  { en: "equivalent", th: "เทียบเท่า", pos: "adj./n.", example: "One dollar is equivalent to 35 baht.", category: "ขั้นสูง" },
  { en: "eradicate", th: "กำจัดให้สิ้น", pos: "v.", example: "We aim to eradicate poverty.", category: "ขั้นสูง" },
  { en: "evaluate", th: "ประเมินค่า", pos: "v.", example: "Please evaluate the results.", category: "ขั้นสูง" },
  { en: "evident", th: "ชัดแจ้ง / ประจักษ์", pos: "adj.", example: "Her talent is evident.", category: "ขั้นสูง" },
  { en: "evoke", th: "กระตุ้น / ทำให้นึกถึง", pos: "v.", example: "The song evokes memories.", category: "ขั้นสูง" },
  { en: "exaggerate", th: "พูดเกินจริง", pos: "v.", example: "Don't exaggerate the problem.", category: "ขั้นสูง" },
  { en: "exceed", th: "เกิน / ล้ำหน้า", pos: "v.", example: "Sales exceeded our expectations.", category: "ขั้นสูง" },
  { en: "exclude", th: "กีดกัน / ไม่รวม", pos: "v.", example: "The price excludes tax.", category: "ขั้นสูง" },
  { en: "exemplify", th: "เป็นตัวอย่างของ", pos: "v.", example: "This case exemplifies the issue.", category: "ขั้นสูง" },
  { en: "exhaust", th: "ทำให้หมดแรง / ใช้จนหมด", pos: "v.", example: "The trip exhausted us.", category: "ขั้นสูง" },
  { en: "explicit", th: "ชัดเจน / โจ่งแจ้ง", pos: "adj.", example: "She gave explicit instructions.", category: "ขั้นสูง" },
  { en: "exploit", th: "ใช้ประโยชน์ / เอาเปรียบ", pos: "v.", example: "They exploit cheap labor.", category: "ขั้นสูง" },
  { en: "extensive", th: "กว้างขวาง / มากมาย", pos: "adj.", example: "He has extensive experience.", category: "ขั้นสูง" },
  { en: "fabricate", th: "กุเรื่อง / ประดิษฐ์ขึ้น", pos: "v.", example: "He fabricated the whole story.", category: "ขั้นสูง" },
  { en: "facilitate", th: "อำนวยความสะดวก", pos: "v.", example: "Technology facilitates learning.", category: "ขั้นสูง" },
  { en: "feasible", th: "ที่เป็นไปได้ / ทำได้จริง", pos: "adj.", example: "Is the plan feasible?", category: "ขั้นสูง" },
  { en: "fluctuate", th: "ขึ้น ๆ ลง ๆ / ผันผวน", pos: "v.", example: "Prices fluctuate daily.", category: "ขั้นสูง" },
  { en: "formidable", th: "น่าเกรงขาม / ยากจะรับมือ", pos: "adj.", example: "They are a formidable team.", category: "ขั้นสูง" },
  { en: "foster", th: "ส่งเสริม / เลี้ยงดู", pos: "v.", example: "We foster creativity in children.", category: "ขั้นสูง" },
  { en: "fragile", th: "เปราะบาง / แตกหักง่าย", pos: "adj.", example: "Handle the glass; it's fragile.", category: "ขั้นสูง" },
  { en: "fundamental", th: "พื้นฐาน / สำคัญยิ่ง", pos: "adj.", example: "Trust is fundamental to friendship.", category: "ขั้นสูง" },
  { en: "generate", th: "ก่อให้เกิด / ผลิต", pos: "v.", example: "Solar panels generate electricity.", category: "ขั้นสูง" },
  { en: "genuine", th: "แท้จริง / จริงใจ", pos: "adj.", example: "She showed genuine concern.", category: "ขั้นสูง" },
  { en: "gratitude", th: "ความรู้สึกขอบคุณ / ความกตัญญู", pos: "n.", example: "I want to express my gratitude.", category: "ขั้นสูง" },
  { en: "hinder", th: "ขัดขวาง / เป็นอุปสรรค", pos: "v.", example: "Bad weather hindered our progress.", category: "ขั้นสูง" },
  { en: "hypothesis", th: "สมมติฐาน", pos: "n.", example: "The experiment tested the hypothesis.", category: "ขั้นสูง" },
  { en: "ideology", th: "อุดมการณ์ / แนวคิด", pos: "n.", example: "They share a political ideology.", category: "ขั้นสูง" },
  { en: "illustrate", th: "แสดงให้เห็น / ยกตัวอย่าง", pos: "v.", example: "Let me illustrate with an example.", category: "ขั้นสูง" },
  { en: "imminent", th: "ที่ใกล้จะเกิด / จวนตัว", pos: "adj.", example: "A storm is imminent.", category: "ขั้นสูง" },
  { en: "impartial", th: "เป็นกลาง / ไม่ลำเอียง", pos: "adj.", example: "A judge must be impartial.", category: "ขั้นสูง" },
  { en: "implement", th: "ดำเนินการ / นำไปปฏิบัติ", pos: "v.", example: "We will implement the new policy.", category: "ขั้นสูง" },
  { en: "implication", th: "นัย / ผลกระทบที่ตามมา", pos: "n.", example: "Consider the implications carefully.", category: "ขั้นสูง" },
  { en: "imply", th: "บอกเป็นนัย", pos: "v.", example: "Are you implying I'm wrong?", category: "ขั้นสูง" },
  { en: "impose", th: "บังคับใช้ / กำหนด", pos: "v.", example: "The government imposed new taxes.", category: "ขั้นสูง" },
  { en: "inadequate", th: "ไม่เพียงพอ", pos: "adj.", example: "The funding was inadequate.", category: "ขั้นสูง" },
  { en: "incentive", th: "แรงจูงใจ / สิ่งกระตุ้น", pos: "n.", example: "Bonuses are a good incentive.", category: "ขั้นสูง" },
  { en: "incline", th: "มีแนวโน้ม / เอนเอียง", pos: "v.", example: "I'm inclined to agree.", category: "ขั้นสูง" },
  { en: "incorporate", th: "รวมเข้าไว้ / ผนวก", pos: "v.", example: "We incorporated their ideas.", category: "ขั้นสูง" },
  { en: "indispensable", th: "ที่ขาดไม่ได้", pos: "adj.", example: "Water is indispensable to life.", category: "ขั้นสูง" },
  { en: "inevitable", th: "ที่หลีกเลี่ยงไม่ได้", pos: "adj.", example: "Change is inevitable.", category: "ขั้นสูง" },
  { en: "infer", th: "อนุมาน / สรุปจากหลักฐาน", pos: "v.", example: "What can we infer from this?", category: "ขั้นสูง" },
  { en: "inherent", th: "ที่มีอยู่ในตัว / โดยกำเนิด", pos: "adj.", example: "There are inherent risks.", category: "ขั้นสูง" },
  { en: "initiate", th: "ริเริ่ม / เริ่มต้น", pos: "v.", example: "She initiated the project.", category: "ขั้นสูง" },
  { en: "innovative", th: "ที่ริเริ่มใหม่ / สร้างสรรค์", pos: "adj.", example: "They have an innovative approach.", category: "ขั้นสูง" },
  { en: "integrity", th: "ความซื่อสัตย์ / ความสมบูรณ์", pos: "n.", example: "He is a man of integrity.", category: "ขั้นสูง" },
  { en: "intricate", th: "ซับซ้อน / ละเอียดอ่อน", pos: "adj.", example: "The design is very intricate.", category: "ขั้นสูง" },
  { en: "intrinsic", th: "ที่เป็นเนื้อแท้ / โดยธรรมชาติ", pos: "adj.", example: "It has intrinsic value.", category: "ขั้นสูง" },
  { en: "intuition", th: "สัญชาตญาณ / ลางสังหรณ์", pos: "n.", example: "Trust your intuition.", category: "ขั้นสูง" },
  { en: "justify", th: "แก้ต่าง / ให้เหตุผลสนับสนุน", pos: "v.", example: "How do you justify this cost?", category: "ขั้นสูง" },
  { en: "legitimate", th: "ถูกต้องตามกฎหมาย / ชอบธรรม", pos: "adj.", example: "That's a legitimate concern.", category: "ขั้นสูง" },
  { en: "leverage", th: "ใช้ประโยชน์ / อำนาจต่อรอง", pos: "v./n.", example: "Leverage your strengths.", category: "ขั้นสูง" },
  { en: "lucrative", th: "ที่ทำกำไรงาม", pos: "adj.", example: "It's a lucrative business.", category: "ขั้นสูง" },
  { en: "magnitude", th: "ขนาด / ความสำคัญ", pos: "n.", example: "The magnitude of the problem is huge.", category: "ขั้นสูง" },
  { en: "meticulous", th: "พิถีพิถัน / ละเอียดรอบคอบ", pos: "adj.", example: "She is meticulous about details.", category: "ขั้นสูง" },
  { en: "mitigate", th: "บรรเทา / ลดทอน", pos: "v.", example: "We must mitigate the risks.", category: "ขั้นสูง" },
  { en: "notion", th: "ความคิด / มโนทัศน์", pos: "n.", example: "I had no notion of the truth.", category: "ขั้นสูง" },
  { en: "notorious", th: "ฉาวโฉ่ / มีชื่อเสียงในทางไม่ดี", pos: "adj.", example: "He is notorious for lying.", category: "ขั้นสูง" },
  { en: "nurture", th: "บ่มเพาะ / เลี้ยงดู", pos: "v.", example: "We nurture young talent.", category: "ขั้นสูง" },
  { en: "objective", th: "วัตถุประสงค์ / เป็นกลาง", pos: "n./adj.", example: "What is your main objective?", category: "ขั้นสูง" },
  { en: "obsolete", th: "ล้าสมัย / เลิกใช้แล้ว", pos: "adj.", example: "That technology is obsolete.", category: "ขั้นสูง" },
  { en: "ominous", th: "ที่เป็นลางร้าย", pos: "adj.", example: "There were ominous clouds.", category: "ขั้นสูง" },
  { en: "optimal", th: "ที่ดีที่สุด / เหมาะที่สุด", pos: "adj.", example: "We seek the optimal solution.", category: "ขั้นสูง" },
  { en: "paramount", th: "สำคัญสูงสุด", pos: "adj.", example: "Safety is paramount.", category: "ขั้นสูง" },
  { en: "peculiar", th: "แปลกประหลาด / เฉพาะตัว", pos: "adj.", example: "It has a peculiar smell.", category: "ขั้นสูง" },
  { en: "perceive", th: "รับรู้ / มองเห็น", pos: "v.", example: "How do you perceive the situation?", category: "ขั้นสูง" },
  { en: "perpetual", th: "ตลอดกาล / ไม่สิ้นสุด", pos: "adj.", example: "He lives in perpetual fear.", category: "ขั้นสูง" },
  { en: "persistent", th: "ที่ยืนกราน / ต่อเนื่อง", pos: "adj.", example: "She is persistent in her efforts.", category: "ขั้นสูง" },
  { en: "plausible", th: "ที่น่าเชื่อถือ / เป็นไปได้", pos: "adj.", example: "That's a plausible explanation.", category: "ขั้นสูง" },
  { en: "pragmatic", th: "ที่เน้นปฏิบัติได้จริง", pos: "adj.", example: "Take a pragmatic approach.", category: "ขั้นสูง" },
  { en: "precede", th: "มาก่อน / นำหน้า", pos: "v.", example: "A storm preceded the calm.", category: "ขั้นสูง" },
  { en: "predominant", th: "ที่มีมากที่สุด / เด่นที่สุด", pos: "adj.", example: "Rice is the predominant crop.", category: "ขั้นสูง" },
  { en: "preliminary", th: "ขั้นต้น / เบื้องต้น", pos: "adj.", example: "These are preliminary results.", category: "ขั้นสูง" },
  { en: "prevail", th: "มีชัย / แพร่หลาย", pos: "v.", example: "Justice will prevail.", category: "ขั้นสูง" },
  { en: "profound", th: "ลึกซึ้ง", pos: "adj.", example: "It had a profound impact.", category: "ขั้นสูง" },
  { en: "prohibit", th: "ห้าม", pos: "v.", example: "Smoking is prohibited here.", category: "ขั้นสูง" },
  { en: "prominent", th: "เด่น / มีชื่อเสียง", pos: "adj.", example: "He is a prominent figure.", category: "ขั้นสูง" },
  { en: "prone", th: "มีแนวโน้มจะ / โน้มเอียง", pos: "adj.", example: "He is prone to mistakes.", category: "ขั้นสูง" },
  { en: "prospective", th: "ที่คาดว่าจะเกิด / ในอนาคต", pos: "adj.", example: "We met prospective clients.", category: "ขั้นสูง" },
  { en: "provoke", th: "ยั่วยุ / กระตุ้น", pos: "v.", example: "Don't provoke him.", category: "ขั้นสูง" },
  { en: "prudent", th: "รอบคอบ / สุขุม", pos: "adj.", example: "It's prudent to save money.", category: "ขั้นสูง" },
  { en: "rational", th: "มีเหตุผล", pos: "adj.", example: "Make a rational decision.", category: "ขั้นสูง" },
  { en: "reconcile", th: "คืนดี / ปรองดอง", pos: "v.", example: "They reconciled after the fight.", category: "ขั้นสูง" },
  { en: "redundant", th: "ที่เกินจำเป็น / ซ้ำซ้อน", pos: "adj.", example: "Remove the redundant words.", category: "ขั้นสูง" },
  { en: "refute", th: "หักล้าง / โต้แย้ง", pos: "v.", example: "She refuted the accusation.", category: "ขั้นสูง" },
  { en: "reinforce", th: "เสริมกำลัง / ตอกย้ำ", pos: "v.", example: "Practice reinforces learning.", category: "ขั้นสูง" },
  { en: "reluctant", th: "ลังเล / ไม่เต็มใจ", pos: "adj.", example: "He was reluctant to help.", category: "ขั้นสูง" },
  { en: "remarkable", th: "น่าทึ่ง / โดดเด่น", pos: "adj.", example: "She made remarkable progress.", category: "ขั้นสูง" },
  { en: "render", th: "ทำให้ / มอบให้", pos: "v.", example: "The injury rendered him helpless.", category: "ขั้นสูง" },
  { en: "resilient", th: "ที่ฟื้นตัวได้ดี / ยืดหยุ่น", pos: "adj.", example: "Children are very resilient.", category: "ขั้นสูง" },
  { en: "resolve", th: "แก้ไข / ตัดสินใจแน่วแน่", pos: "v.", example: "We must resolve this issue.", category: "ขั้นสูง" },
  { en: "retain", th: "เก็บรักษา / คงไว้", pos: "v.", example: "Try to retain the information.", category: "ขั้นสูง" },
  { en: "retrieve", th: "ค้นคืน / เอากลับมา", pos: "v.", example: "I retrieved my lost files.", category: "ขั้นสูง" },
  { en: "rigorous", th: "เข้มงวด / เคร่งครัด", pos: "adj.", example: "The training is rigorous.", category: "ขั้นสูง" },
  { en: "robust", th: "แข็งแกร่ง / ทนทาน", pos: "adj.", example: "We need a robust system.", category: "ขั้นสูง" },
  { en: "scrutiny", th: "การตรวจสอบอย่างละเอียด", pos: "n.", example: "The plan is under scrutiny.", category: "ขั้นสูง" },
  { en: "simultaneous", th: "ที่เกิดขึ้นพร้อมกัน", pos: "adj.", example: "There were simultaneous explosions.", category: "ขั้นสูง" },
  { en: "skeptical", th: "ที่ขี้สงสัย / ไม่เชื่อง่าย", pos: "adj.", example: "I'm skeptical about the claim.", category: "ขั้นสูง" },
  { en: "sophisticated", th: "ซับซ้อน / ทันสมัย", pos: "adj.", example: "It's a sophisticated machine.", category: "ขั้นสูง" },
  { en: "spontaneous", th: "ที่เกิดขึ้นเอง / ฉับพลัน", pos: "adj.", example: "It was a spontaneous decision.", category: "ขั้นสูง" },
  { en: "stagnant", th: "ที่หยุดนิ่ง / ซบเซา", pos: "adj.", example: "The economy is stagnant.", category: "ขั้นสูง" },
  { en: "subtle", th: "ละเอียดอ่อน / แนบเนียน", pos: "adj.", example: "There's a subtle difference.", category: "ขั้นสูง" },
  { en: "sufficient", th: "เพียงพอ", pos: "adj.", example: "We have sufficient supplies.", category: "ขั้นสูง" },
  { en: "supplement", th: "เสริม / สิ่งเสริม", pos: "v./n.", example: "He takes vitamin supplements.", category: "ขั้นสูง" },
  { en: "suppress", th: "กดข่ม / ระงับ", pos: "v.", example: "She suppressed her anger.", category: "ขั้นสูง" },
  { en: "susceptible", th: "ที่อ่อนไหวต่อ / เสี่ยงต่อ", pos: "adj.", example: "He is susceptible to colds.", category: "ขั้นสูง" },
  { en: "sustain", th: "ค้ำจุน / ทำให้ดำเนินต่อ", pos: "v.", example: "Can we sustain this growth?", category: "ขั้นสูง" },
  { en: "tangible", th: "ที่จับต้องได้ / เป็นรูปธรรม", pos: "adj.", example: "We need tangible results.", category: "ขั้นสูง" },
  { en: "tedious", th: "น่าเบื่อ / จำเจ", pos: "adj.", example: "It was a tedious task.", category: "ขั้นสูง" },
  { en: "tentative", th: "ที่ยังไม่แน่นอน / ชั่วคราว", pos: "adj.", example: "We made tentative plans.", category: "ขั้นสูง" },
  { en: "thorough", th: "ละเอียดถี่ถ้วน", pos: "adj.", example: "She did a thorough job.", category: "ขั้นสูง" },
  { en: "transparent", th: "โปร่งใส / ชัดเจน", pos: "adj.", example: "We need a transparent process.", category: "ขั้นสูง" },
  { en: "trivial", th: "เล็กน้อย / ไม่สำคัญ", pos: "adj.", example: "Don't worry about trivial matters.", category: "ขั้นสูง" },
  { en: "ubiquitous", th: "ที่มีอยู่ทุกหนแห่ง", pos: "adj.", example: "Smartphones are ubiquitous.", category: "ขั้นสูง" },
  { en: "unanimous", th: "ที่เป็นเอกฉันท์", pos: "adj.", example: "The vote was unanimous.", category: "ขั้นสูง" },
  { en: "underlying", th: "ที่เป็นรากฐาน / แฝงอยู่", pos: "adj.", example: "What is the underlying cause?", category: "ขั้นสูง" },
  { en: "undertake", th: "ลงมือทำ / รับภาระ", pos: "v.", example: "They undertook a huge project.", category: "ขั้นสูง" },
  { en: "versatile", th: "ที่อเนกประสงค์ / มีความสามารถหลากหลาย", pos: "adj.", example: "She is a versatile artist.", category: "ขั้นสูง" },
  { en: "viable", th: "ที่ทำได้จริง / อยู่รอดได้", pos: "adj.", example: "Is this a viable option?", category: "ขั้นสูง" },
  { en: "vivid", th: "ชัดเจนแจ่มชัด / สดใส", pos: "adj.", example: "I have a vivid memory of it.", category: "ขั้นสูง" },
  { en: "coincidence", th: "เรื่องบังเอิญ", pos: "n.", example: "What a coincidence to meet you here!", category: "ขั้นสูง" },
  { en: "diplomatic", th: "ที่มีไหวพริบ / เชิงการทูต", pos: "adj.", example: "She gave a diplomatic answer.", category: "ขั้นสูง" },
  { en: "discern", th: "มองออก / แยกแยะ", pos: "v.", example: "It's hard to discern the difference.", category: "ขั้นสูง" },
  { en: "elicit", th: "ดึงออกมา / ทำให้เกิด (การตอบสนอง)", pos: "v.", example: "The question elicited a strong reaction.", category: "ขั้นสูง" },
  { en: "inquiry", th: "การสอบถาม / การสืบสวน", pos: "n.", example: "We received many inquiries.", category: "ขั้นสูง" },
  { en: "compelling", th: "ที่น่าสนใจ / โน้มน้าวใจ", pos: "adj.", example: "She made a compelling argument.", category: "ขั้นสูง" },
  { en: "advocacy", th: "การสนับสนุน / การรณรงค์", pos: "n.", example: "Her advocacy changed the law.", category: "ขั้นสูง" },
  { en: "comprehend", th: "เข้าใจ / หยั่งรู้", pos: "v.", example: "It's hard to comprehend the scale.", category: "ขั้นสูง" },
  { en: "conscientious", th: "ที่มีสำนึกรับผิดชอบ / รอบคอบ", pos: "adj.", example: "He is a conscientious worker.", category: "ขั้นสูง" },
  { en: "vulnerable", th: "ที่เปราะบาง / อ่อนแอต่อภัย", pos: "adj.", example: "Children are especially vulnerable.", category: "ขั้นสูง" },

  // ===== สำนวน (Common idioms) — สำนวนภาษาอังกฤษที่ใช้บ่อย =====
  { en: "a piece of cake", th: "ง่ายมาก / กล้วย ๆ", pos: "idiom", example: "The exam was a piece of cake.", category: "สำนวน" },
  { en: "break the ice", th: "ละลายพฤติกรรม / ทำลายความเงียบ", pos: "idiom", example: "He told a joke to break the ice.", category: "สำนวน" },
  { en: "under the weather", th: "รู้สึกไม่สบาย", pos: "idiom", example: "I'm feeling a bit under the weather today.", category: "สำนวน" },
  { en: "hit the books", th: "ตั้งใจอ่านหนังสือ", pos: "idiom", example: "I have to hit the books tonight.", category: "สำนวน" },
  { en: "once in a blue moon", th: "นาน ๆ ครั้ง", pos: "idiom", example: "We meet once in a blue moon.", category: "สำนวน" },
  { en: "cost an arm and a leg", th: "แพงมาก", pos: "idiom", example: "This phone cost an arm and a leg.", category: "สำนวน" },
  { en: "break a leg", th: "ขอให้โชคดี (ก่อนขึ้นแสดง)", pos: "idiom", example: "Break a leg in your performance!", category: "สำนวน" },
  { en: "call it a day", th: "เลิก / พอแค่นี้", pos: "idiom", example: "Let's call it a day and go home.", category: "สำนวน" },
  { en: "on the same page", th: "เข้าใจตรงกัน", pos: "idiom", example: "Let's make sure we're on the same page.", category: "สำนวน" },
  { en: "out of the blue", th: "อยู่ดี ๆ / ไม่คาดคิด", pos: "idiom", example: "She called me out of the blue.", category: "สำนวน" },
  { en: "get cold feet", th: "ลังเล / ใจฝ่อขึ้นมา", pos: "idiom", example: "He got cold feet before the wedding.", category: "สำนวน" },
  { en: "bite the bullet", th: "กัดฟันทำ / ทำสิ่งที่ยาก", pos: "idiom", example: "I bit the bullet and apologized.", category: "สำนวน" },
  { en: "hit the sack", th: "เข้านอน", pos: "idiom", example: "I'm tired; I'll hit the sack.", category: "สำนวน" },
  { en: "let the cat out of the bag", th: "เผลอบอกความลับ", pos: "idiom", example: "Don't let the cat out of the bag.", category: "สำนวน" },
  { en: "the ball is in your court", th: "ถึงตาคุณตัดสินใจ", pos: "idiom", example: "I've done my part; the ball is in your court.", category: "สำนวน" },
  { en: "speak of the devil", th: "พูดถึงใครคนนั้นก็มาพอดี", pos: "idiom", example: "Speak of the devil — here she comes!", category: "สำนวน" },
  { en: "a blessing in disguise", th: "สิ่งดีที่แฝงมาในรูปร้าย", pos: "idiom", example: "Losing that job was a blessing in disguise.", category: "สำนวน" },
  { en: "cut corners", th: "ทำแบบลวก ๆ เพื่อประหยัด", pos: "idiom", example: "Don't cut corners on safety.", category: "สำนวน" },
  { en: "pull someone's leg", th: "ล้อเล่น / แกล้ง", pos: "idiom", example: "Relax, I'm just pulling your leg.", category: "สำนวน" },
  { en: "see eye to eye", th: "เห็นพ้องต้องกัน", pos: "idiom", example: "We don't always see eye to eye.", category: "สำนวน" },
  { en: "burn the midnight oil", th: "ทำงาน/อ่านหนังสือดึกดื่น", pos: "idiom", example: "She burned the midnight oil before the test.", category: "สำนวน" },
  { en: "miss the boat", th: "พลาดโอกาส", pos: "idiom", example: "If you wait too long, you'll miss the boat.", category: "สำนวน" },
  { en: "the last straw", th: "ฟางเส้นสุดท้าย / ที่ทนได้", pos: "idiom", example: "His rude comment was the last straw.", category: "สำนวน" },
  { en: "ring a bell", th: "คุ้น ๆ / พอนึกออก", pos: "idiom", example: "That name rings a bell.", category: "สำนวน" },
  { en: "in a nutshell", th: "สรุปสั้น ๆ", pos: "idiom", example: "In a nutshell, we need more time.", category: "สำนวน" },
  { en: "back to the drawing board", th: "เริ่มต้นใหม่ / คิดใหม่", pos: "idiom", example: "The plan failed, so it's back to the drawing board.", category: "สำนวน" },
  { en: "beat around the bush", th: "พูดอ้อมค้อม", pos: "idiom", example: "Stop beating around the bush and tell me.", category: "สำนวน" },
  { en: "give someone a hand", th: "ช่วยเหลือ", pos: "idiom", example: "Could you give me a hand with this?", category: "สำนวน" },
  { en: "keep an eye on", th: "คอยจับตาดู / เฝ้าระวัง", pos: "idiom", example: "Please keep an eye on my bag.", category: "สำนวน" },
  { en: "make up your mind", th: "ตัดสินใจ", pos: "idiom", example: "Hurry up and make up your mind.", category: "สำนวน" },
  { en: "no pain, no gain", th: "ไม่ลงทุนไม่ได้ผล / ไม่เจ็บไม่โต", pos: "idiom", example: "Keep training — no pain, no gain.", category: "สำนวน" },
  { en: "better late than never", th: "มาช้าดีกว่าไม่มา", pos: "idiom", example: "He finally apologized — better late than never.", category: "สำนวน" },
  { en: "easier said than done", th: "พูดง่ายกว่าทำ", pos: "idiom", example: "Quitting sugar is easier said than done.", category: "สำนวน" },
  { en: "the early bird catches the worm", th: "ตื่นเช้า/มาก่อนได้เปรียบ", pos: "idiom", example: "Arrive early — the early bird catches the worm.", category: "สำนวน" },
  { en: "actions speak louder than words", th: "ทำให้ดูดีกว่าพูด", pos: "idiom", example: "Don't just promise — actions speak louder than words.", category: "สำนวน" },

  // ===== อีเมลธุรกิจ (Business email) =====
  { en: "I am writing to...", th: "ผมเขียนมาเพื่อ...", pos: "phrase", example: "I am writing to inquire about your services.", category: "อีเมลธุรกิจ" },
  { en: "With reference to", th: "อ้างถึง / เกี่ยวกับ", pos: "phrase", example: "With reference to your email of June 1...", category: "อีเมลธุรกิจ" },
  { en: "Please find attached", th: "กรุณาดูไฟล์แนบ", pos: "phrase", example: "Please find attached the monthly report.", category: "อีเมลธุรกิจ" },
  { en: "I have attached", th: "ผมได้แนบ...มาด้วย", pos: "phrase", example: "I have attached the invoice for your reference.", category: "อีเมลธุรกิจ" },
  { en: "attachment", th: "ไฟล์แนบ", pos: "n.", example: "Please open the attachment.", category: "อีเมลธุรกิจ" },
  { en: "as per our conversation", th: "ตามที่เราได้คุยกัน", pos: "phrase", example: "As per our conversation, I'm sending the quote.", category: "อีเมลธุรกิจ" },
  { en: "as requested", th: "ตามที่ร้องขอ", pos: "phrase", example: "As requested, here are the figures.", category: "อีเมลธุรกิจ" },
  { en: "for your reference", th: "เพื่อเป็นข้อมูลอ้างอิงของคุณ", pos: "phrase", example: "I'm sending this for your reference.", category: "อีเมลธุรกิจ" },
  { en: "Could you please confirm", th: "กรุณายืนยัน", pos: "phrase", example: "Could you please confirm your availability?", category: "อีเมลธุรกิจ" },
  { en: "to acknowledge receipt", th: "แจ้งยืนยันว่าได้รับแล้ว", pos: "phrase", example: "Please acknowledge receipt of this email.", category: "อีเมลธุรกิจ" },
  { en: "at your earliest convenience", th: "เมื่อคุณสะดวกที่สุด (โดยเร็ว)", pos: "phrase", example: "Please reply at your earliest convenience.", category: "อีเมลธุรกิจ" },
  { en: "Thank you for your prompt reply", th: "ขอบคุณที่ตอบกลับอย่างรวดเร็ว", pos: "phrase", example: "Thank you for your prompt reply to my request.", category: "อีเมลธุรกิจ" },
  { en: "I apologize for the late reply", th: "ขออภัยที่ตอบกลับช้า", pos: "phrase", example: "I apologize for the late reply; I was traveling.", category: "อีเมลธุรกิจ" },
  { en: "I regret to inform you", th: "ผมเสียใจที่ต้องแจ้งว่า", pos: "phrase", example: "I regret to inform you that the order is delayed.", category: "อีเมลธุรกิจ" },
  { en: "I would appreciate it if", th: "ผมจะขอบคุณมากหาก", pos: "phrase", example: "I would appreciate it if you could reply by Friday.", category: "อีเมลธุรกิจ" },
  { en: "on behalf of", th: "ในนามของ", pos: "phrase", example: "I'm writing on behalf of our company.", category: "อีเมลธุรกิจ" },
  { en: "Please do not hesitate to contact me", th: "อย่าลังเลที่จะติดต่อผม", pos: "phrase", example: "Please do not hesitate to contact me with questions.", category: "อีเมลธุรกิจ" },
  { en: "Please let me know if you have any questions", th: "แจ้งได้หากมีคำถาม", pos: "phrase", example: "Please let me know if you have any questions.", category: "อีเมลธุรกิจ" },
  { en: "Thank you in advance", th: "ขอบคุณล่วงหน้า", pos: "phrase", example: "Thank you in advance for your help.", category: "อีเมลธุรกิจ" },
  { en: "I look forward to hearing from you", th: "ผมรอการติดต่อกลับจากคุณ", pos: "phrase", example: "I look forward to hearing from you soon.", category: "อีเมลธุรกิจ" },
  { en: "Best regards", th: "ด้วยความเคารพ (คำลงท้ายอีเมล)", pos: "phrase", example: "Best regards, John Smith.", category: "อีเมลธุรกิจ" },
  { en: "Kind regards", th: "ด้วยความนับถือ (คำลงท้าย)", pos: "phrase", example: "Kind regards, the Sales Team.", category: "อีเมลธุรกิจ" },

  // ===== ประชุม & เจรจา (Meetings & negotiation) =====
  { en: "agenda", th: "วาระการประชุม", pos: "n.", example: "Let's stick to the agenda.", category: "ประชุม & เจรจา" },
  { en: "minutes", th: "รายงานการประชุม", pos: "n.", example: "Could you send me the minutes of the meeting?", category: "ประชุม & เจรจา" },
  { en: "to schedule a meeting", th: "นัดประชุม", pos: "phrase", example: "Let's schedule a meeting for next week.", category: "ประชุม & เจรจา" },
  { en: "Shall we begin?", th: "เราเริ่มกันได้ไหม", pos: "phrase", example: "Everyone is here. Shall we begin?", category: "ประชุม & เจรจา" },
  { en: "Let's get started", th: "เริ่มกันเลย", pos: "phrase", example: "Let's get started; we have a lot to cover.", category: "ประชุม & เจรจา" },
  { en: "Let's move on to the next point", th: "ไปประเด็นถัดไปกัน", pos: "phrase", example: "Good. Let's move on to the next point.", category: "ประชุม & เจรจา" },
  { en: "to bring up", th: "หยิบยกขึ้นมา (พูดถึง)", pos: "phrase", example: "I'd like to bring up the budget issue.", category: "ประชุม & เจรจา" },
  { en: "Could you elaborate on that?", th: "ช่วยขยายความเรื่องนั้นได้ไหม", pos: "phrase", example: "Interesting. Could you elaborate on that?", category: "ประชุม & เจรจา" },
  { en: "I see your point", th: "ผมเข้าใจประเด็นของคุณ", pos: "phrase", example: "I see your point, but I have a concern.", category: "ประชุม & เจรจา" },
  { en: "I'm afraid I disagree", th: "ผมเกรงว่าจะไม่เห็นด้วย", pos: "phrase", example: "I'm afraid I disagree with that approach.", category: "ประชุม & เจรจา" },
  { en: "Let's table that for now", th: "พักเรื่องนั้นไว้ก่อน", pos: "phrase", example: "Let's table that for now and come back later.", category: "ประชุม & เจรจา" },
  { en: "to reach an agreement", th: "บรรลุข้อตกลง", pos: "phrase", example: "I'm sure we can reach an agreement.", category: "ประชุม & เจรจา" },
  { en: "to negotiate", th: "เจรจาต่อรอง", pos: "v.", example: "We need to negotiate the price.", category: "ประชุม & เจรจา" },
  { en: "counteroffer", th: "ข้อเสนอโต้กลับ", pos: "n.", example: "They made a counteroffer.", category: "ประชุม & เจรจา" },
  { en: "win-win", th: "ได้ประโยชน์ทั้งสองฝ่าย", pos: "adj.", example: "It's a win-win situation for both sides.", category: "ประชุม & เจรจา" },
  { en: "terms and conditions", th: "ข้อตกลงและเงื่อนไข", pos: "n.", example: "Please review the terms and conditions.", category: "ประชุม & เจรจา" },
  { en: "stakeholder", th: "ผู้มีส่วนได้ส่วนเสีย", pos: "n.", example: "We must consult all the stakeholders.", category: "ประชุม & เจรจา" },
  { en: "action items", th: "สิ่งที่ต้องไปทำต่อ", pos: "n.", example: "Let's review the action items before we finish.", category: "ประชุม & เจรจา" },
  { en: "to delegate", th: "มอบหมายงาน", pos: "v.", example: "A good manager knows how to delegate.", category: "ประชุม & เจรจา" },
  { en: "Let's recap", th: "ขอทบทวนสรุป", pos: "phrase", example: "Let's recap what we've decided.", category: "ประชุม & เจรจา" },
  { en: "to wrap up", th: "สรุปปิดท้าย", pos: "phrase", example: "Let's wrap up the meeting.", category: "ประชุม & เจรจา" },
  { en: "I'll get back to you", th: "เดี๋ยวผมติดต่อกลับ", pos: "phrase", example: "I'll get back to you on that tomorrow.", category: "ประชุม & เจรจา" },

  // ===== โทรศัพท์ & นัดหมาย (Calls & scheduling) =====
  { en: "May I speak to...?", th: "ขอสายคุณ...", pos: "phrase", example: "Hello, may I speak to Mr. Lee?", category: "โทรศัพท์ & นัดหมาย" },
  { en: "Speaking.", th: "กำลังพูดสายอยู่ (ผมเอง)", pos: "phrase", example: "Is this Mr. Lee? — Speaking.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "I'm calling regarding...", th: "ผมโทรมาเรื่อง...", pos: "phrase", example: "I'm calling regarding your order.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "Hold on, please.", th: "กรุณาถือสายรอสักครู่", pos: "phrase", example: "Hold on, please. I'll check.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "I'll put you through", th: "ผมจะโอนสายให้", pos: "phrase", example: "I'll put you through to the manager.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "Can I take a message?", th: "จะฝากข้อความไว้ไหม", pos: "phrase", example: "He's not here. Can I take a message?", category: "โทรศัพท์ & นัดหมาย" },
  { en: "Could you call back later?", th: "โทรกลับมาภายหลังได้ไหม", pos: "phrase", example: "She's busy. Could you call back later?", category: "โทรศัพท์ & นัดหมาย" },
  { en: "The line is busy", th: "สายไม่ว่าง", pos: "phrase", example: "The line is busy; please try again.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "to set up an appointment", th: "นัดหมาย", pos: "phrase", example: "I'd like to set up an appointment.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "to confirm an appointment", th: "ยืนยันนัด", pos: "phrase", example: "I'm calling to confirm our appointment.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "to reschedule", th: "เลื่อนนัด", pos: "v.", example: "Can we reschedule to Thursday?", category: "โทรศัพท์ & นัดหมาย" },
  { en: "to call off", th: "ยกเลิก", pos: "phrase", example: "We had to call off the meeting.", category: "โทรศัพท์ & นัดหมาย" },
  { en: "Are you available on...?", th: "คุณว่างวัน...ไหม", pos: "phrase", example: "Are you available on Monday morning?", category: "โทรศัพท์ & นัดหมาย" },
  { en: "Let me check my schedule", th: "ขอเช็กตารางเวลาก่อน", pos: "phrase", example: "Let me check my schedule and get back to you.", category: "โทรศัพท์ & นัดหมาย" },

  // ===== การเงิน & การค้า (Finance & commerce) =====
  { en: "invoice", th: "ใบแจ้งหนี้", pos: "n.", example: "We will send the invoice by email.", category: "การเงิน & การค้า" },
  { en: "quotation", th: "ใบเสนอราคา", pos: "n.", example: "Could you send us a quotation?", category: "การเงิน & การค้า" },
  { en: "estimate", th: "ประมาณการ / ใบประเมินราคา", pos: "n./v.", example: "Can you give me an estimate of the cost?", category: "การเงิน & การค้า" },
  { en: "budget", th: "งบประมาณ", pos: "n.", example: "The project is over budget.", category: "การเงิน & การค้า" },
  { en: "revenue", th: "รายได้", pos: "n.", example: "Annual revenue increased by 10%.", category: "การเงิน & การค้า" },
  { en: "profit", th: "กำไร", pos: "n.", example: "The company made a healthy profit.", category: "การเงิน & การค้า" },
  { en: "loss", th: "ขาดทุน", pos: "n.", example: "We reported a loss last quarter.", category: "การเงิน & การค้า" },
  { en: "expense", th: "ค่าใช้จ่าย", pos: "n.", example: "We need to cut expenses.", category: "การเงิน & การค้า" },
  { en: "cash flow", th: "กระแสเงินสด", pos: "n.", example: "Good cash flow is vital for a business.", category: "การเงิน & การค้า" },
  { en: "turnover", th: "ยอดขาย / อัตราหมุนเวียน", pos: "n.", example: "The company has a high annual turnover.", category: "การเงิน & การค้า" },
  { en: "payment terms", th: "เงื่อนไขการชำระเงิน", pos: "n.", example: "Our payment terms are 30 days.", category: "การเงิน & การค้า" },
  { en: "deposit", th: "เงินมัดจำ", pos: "n.", example: "A 20% deposit is required.", category: "การเงิน & การค้า" },
  { en: "refund", th: "การคืนเงิน", pos: "n.", example: "You can request a refund within 14 days.", category: "การเงิน & การค้า" },
  { en: "discount", th: "ส่วนลด", pos: "n.", example: "We offer a 10% discount for bulk orders.", category: "การเงิน & การค้า" },
  { en: "receipt", th: "ใบเสร็จรับเงิน", pos: "n.", example: "Please keep your receipt.", category: "การเงิน & การค้า" },
  { en: "purchase order", th: "ใบสั่งซื้อ", pos: "n.", example: "Please send the purchase order today.", category: "การเงิน & การค้า" },
  { en: "to place an order", th: "สั่งซื้อสินค้า", pos: "phrase", example: "I'd like to place an order for 100 units.", category: "การเงิน & การค้า" },
  { en: "due date", th: "วันครบกำหนด (ชำระ/ส่ง)", pos: "n.", example: "The due date for payment is the 15th.", category: "การเงิน & การค้า" },
  { en: "overdue", th: "เกินกำหนดชำระ", pos: "adj.", example: "The invoice is two weeks overdue.", category: "การเงิน & การค้า" },
  { en: "to settle an invoice", th: "ชำระใบแจ้งหนี้", pos: "phrase", example: "Please settle the invoice by month-end.", category: "การเงิน & การค้า" },
  { en: "transaction", th: "ธุรกรรม / รายการซื้อขาย", pos: "n.", example: "The transaction was completed successfully.", category: "การเงิน & การค้า" },
  { en: "supplier", th: "ผู้จัดหา / ซัพพลายเออร์", pos: "n.", example: "We are looking for a new supplier.", category: "การเงิน & การค้า" },
  { en: "shipment", th: "การจัดส่งสินค้า", pos: "n.", example: "The shipment will arrive on Friday.", category: "การเงิน & การค้า" },
  { en: "warranty", th: "การรับประกัน", pos: "n.", example: "The product comes with a one-year warranty.", category: "การเงิน & การค้า" },
  { en: "in stock", th: "มีสินค้าในคลัง", pos: "phrase", example: "The item is currently in stock.", category: "การเงิน & การค้า" },
  { en: "out of stock", th: "สินค้าหมด", pos: "phrase", example: "I'm sorry, that model is out of stock.", category: "การเงิน & การค้า" },
  { en: "wholesale", th: "ขายส่ง", pos: "n./adj.", example: "We buy these at wholesale prices.", category: "การเงิน & การค้า" },
  { en: "retail", th: "ขายปลีก", pos: "n./adj.", example: "The retail price is higher.", category: "การเงิน & การค้า" },

  // ===== วลีมืออาชีพ (Professional & polite phrases) =====
  { en: "I'd be happy to help", th: "ผมยินดีช่วยเหลือ", pos: "phrase", example: "I'd be happy to help with that.", category: "วลีมืออาชีพ" },
  { en: "Would it be possible to...?", th: "จะเป็นไปได้ไหมที่จะ...", pos: "phrase", example: "Would it be possible to move the deadline?", category: "วลีมืออาชีพ" },
  { en: "I'm afraid that...", th: "ผมเกรงว่า... (บอกข่าวไม่ดีอย่างสุภาพ)", pos: "phrase", example: "I'm afraid that won't be possible.", category: "วลีมืออาชีพ" },
  { en: "Let me get back to you on that", th: "ขอกลับไปตอบเรื่องนั้นนะ", pos: "phrase", example: "Good question. Let me get back to you on that.", category: "วลีมืออาชีพ" },
  { en: "with all due respect", th: "ด้วยความเคารพ (ก่อนจะแย้ง)", pos: "phrase", example: "With all due respect, I think we should wait.", category: "วลีมืออาชีพ" },
  { en: "Could you clarify...?", th: "ช่วยอธิบายให้ชัดเจน...", pos: "phrase", example: "Could you clarify what you mean?", category: "วลีมืออาชีพ" },
  { en: "I'm not sure I follow", th: "ผมไม่ค่อยเข้าใจที่คุณพูด", pos: "phrase", example: "Sorry, I'm not sure I follow.", category: "วลีมืออาชีพ" },
  { en: "Let me clarify", th: "ขออธิบายให้ชัดเจน", pos: "phrase", example: "Let me clarify my last point.", category: "วลีมืออาชีพ" },
  { en: "Thank you for your patience", th: "ขอบคุณที่อดทนรอ", pos: "phrase", example: "Thank you for your patience during the delay.", category: "วลีมืออาชีพ" },
  { en: "I appreciate your understanding", th: "ขอบคุณในความเข้าใจ", pos: "phrase", example: "I appreciate your understanding in this matter.", category: "วลีมืออาชีพ" },
  { en: "Please bear with me", th: "กรุณาอดทนรอสักครู่", pos: "phrase", example: "Please bear with me while I check.", category: "วลีมืออาชีพ" },
  { en: "That works for me", th: "แบบนั้นโอเคสำหรับผม", pos: "phrase", example: "Friday at 2 p.m.? That works for me.", category: "วลีมืออาชีพ" },
  { en: "I'll keep you posted", th: "ผมจะคอยอัปเดตให้", pos: "phrase", example: "I'll keep you posted on any changes.", category: "วลีมืออาชีพ" },
  { en: "Let's keep in touch", th: "ติดต่อกันไว้นะ", pos: "phrase", example: "It was great meeting you. Let's keep in touch.", category: "วลีมืออาชีพ" },
  { en: "to be in charge of", th: "รับผิดชอบดูแล", pos: "phrase", example: "She is in charge of the marketing team.", category: "วลีมืออาชีพ" },
  { en: "to be responsible for", th: "รับผิดชอบ (งาน/หน้าที่)", pos: "phrase", example: "I'm responsible for customer support.", category: "วลีมืออาชีพ" },
  { en: "to meet a deadline", th: "ส่งงานทันกำหนด", pos: "phrase", example: "We must meet the deadline.", category: "วลีมืออาชีพ" },
  { en: "to take into account", th: "คำนึงถึง / นำมาพิจารณา", pos: "phrase", example: "We should take the cost into account.", category: "วลีมืออาชีพ" },
  { en: "as soon as possible", th: "โดยเร็วที่สุด", pos: "phrase", example: "Please reply as soon as possible.", category: "วลีมืออาชีพ" },
  { en: "in the meantime", th: "ในระหว่างนี้", pos: "phrase", example: "In the meantime, please review the draft.", category: "วลีมืออาชีพ" }
];
