// Word-family forms: maps a headword -> its forms as different parts of speech.
// Shown on the back of the card so learners see how a word changes between
// noun / verb / adjective / adverb. Only the forms that commonly exist are
// listed. Words not in this map simply show no word-family line.
//
// Keys: n = noun, v = verb, adj = adjective, adv = adverb.
const WORD_FORMS = {
  abundant: { n: "abundance", adj: "abundant", adv: "abundantly" },
  accomplish: { n: "accomplishment", v: "accomplish", adj: "accomplished" },
  accurate: { n: "accuracy", adj: "accurate", adv: "accurately" },
  acknowledge: { n: "acknowledgment", v: "acknowledge" },
  acquire: { n: "acquisition", v: "acquire" },
  adequate: { n: "adequacy", adj: "adequate", adv: "adequately" },
  advocate: { n: "advocacy", v: "advocate" },
  aesthetic: { n: "aesthetics", adj: "aesthetic", adv: "aesthetically" },
  allocate: { n: "allocation", v: "allocate" },
  ambiguous: { n: "ambiguity", adj: "ambiguous", adv: "ambiguously" },
  analyze: { n: "analysis", v: "analyze", adj: "analytical", adv: "analytically" },
  anticipate: { n: "anticipation", v: "anticipate", adj: "anticipated" },
  apparent: { adj: "apparent", adv: "apparently" },
  arbitrary: { n: "arbitrariness", adj: "arbitrary", adv: "arbitrarily" },
  articulate: { n: "articulation", v: "articulate", adj: "articulate" },
  aspire: { n: "aspiration", v: "aspire", adj: "aspiring" },
  assess: { n: "assessment", v: "assess" },
  assume: { n: "assumption", v: "assume" },
  attain: { n: "attainment", v: "attain", adj: "attainable" },
  authentic: { n: "authenticity", adj: "authentic", adv: "authentically" },
  benevolent: { n: "benevolence", adj: "benevolent" },
  bias: { n: "bias", adj: "biased" },
  brilliant: { n: "brilliance", adj: "brilliant", adv: "brilliantly" },
  candid: { n: "candor", adj: "candid", adv: "candidly" },
  capacity: { n: "capacity", adj: "capable" },
  cease: { n: "cessation", v: "cease", adj: "ceaseless" },
  coherent: { n: "coherence", adj: "coherent", adv: "coherently" },
  coincide: { n: "coincidence", v: "coincide", adj: "coincidental", adv: "coincidentally" },
  collaborate: { n: "collaboration", v: "collaborate", adj: "collaborative" },
  commence: { n: "commencement", v: "commence" },
  compel: { v: "compel", adj: "compelling" },
  compensate: { n: "compensation", v: "compensate", adj: "compensatory" },
  competent: { n: "competence", adj: "competent", adv: "competently" },
  comprehend: { n: "comprehension", v: "comprehend", adj: "comprehensible" },
  comprehensive: { adj: "comprehensive", adv: "comprehensively" },
  conceive: { n: "conception", v: "conceive", adj: "conceivable", adv: "conceivably" },
  concise: { n: "conciseness", adj: "concise", adv: "concisely" },
  condemn: { n: "condemnation", v: "condemn" },
  conform: { n: "conformity", v: "conform", adj: "conformist" },
  consequence: { n: "consequence", adj: "consequent", adv: "consequently" },
  conserve: { n: "conservation", v: "conserve", adj: "conservative" },
  consistent: { n: "consistency", adj: "consistent", adv: "consistently" },
  conspicuous: { adj: "conspicuous", adv: "conspicuously" },
  constitute: { n: "constitution", v: "constitute", adj: "constitutional" },
  contemplate: { n: "contemplation", v: "contemplate", adj: "contemplative" },
  contradict: { n: "contradiction", v: "contradict", adj: "contradictory" },
  controversial: { n: "controversy", adj: "controversial", adv: "controversially" },
  convey: { n: "conveyance", v: "convey" },
  crucial: { adj: "crucial", adv: "crucially" },
  cumulative: { n: "accumulation", v: "accumulate", adj: "cumulative" },
  deduce: { n: "deduction", v: "deduce", adj: "deductive" },
  deficient: { n: "deficiency", adj: "deficient" },
  deliberate: { n: "deliberation", v: "deliberate", adj: "deliberate", adv: "deliberately" },
  demonstrate: { n: "demonstration", v: "demonstrate", adj: "demonstrable" },
  deteriorate: { n: "deterioration", v: "deteriorate" },
  diligent: { n: "diligence", adj: "diligent", adv: "diligently" },
  distinct: { n: "distinction", v: "distinguish", adj: "distinct", adv: "distinctly" },
  diverse: { n: "diversity", v: "diversify", adj: "diverse", adv: "diversely" },
  dominant: { n: "dominance", v: "dominate", adj: "dominant" },
  dubious: { adj: "dubious", adv: "dubiously" },
  eligible: { n: "eligibility", adj: "eligible" },
  eloquent: { n: "eloquence", adj: "eloquent", adv: "eloquently" },
  elaborate: { n: "elaboration", v: "elaborate", adj: "elaborate", adv: "elaborately" },
  emerge: { n: "emergence", v: "emerge", adj: "emergent" },
  eminent: { n: "eminence", adj: "eminent", adv: "eminently" },
  empirical: { adj: "empirical", adv: "empirically" },
  endorse: { n: "endorsement", v: "endorse" },
  enhance: { n: "enhancement", v: "enhance" },
  enormous: { n: "enormity", adj: "enormous", adv: "enormously" },
  equivalent: { n: "equivalence", adj: "equivalent" },
  eradicate: { n: "eradication", v: "eradicate" },
  evaluate: { n: "evaluation", v: "evaluate", adj: "evaluative" },
  evident: { n: "evidence", adj: "evident", adv: "evidently" },
  evoke: { n: "evocation", v: "evoke", adj: "evocative" },
  exaggerate: { n: "exaggeration", v: "exaggerate", adj: "exaggerated" },
  exceed: { n: "excess", v: "exceed", adj: "excessive", adv: "excessively" },
  exclude: { n: "exclusion", v: "exclude", adj: "exclusive", adv: "exclusively" },
  exemplify: { n: "example", v: "exemplify", adj: "exemplary" },
  exhaust: { n: "exhaustion", v: "exhaust", adj: "exhausting" },
  explicit: { adj: "explicit", adv: "explicitly" },
  exploit: { n: "exploitation", v: "exploit", adj: "exploitative" },
  extensive: { n: "extent", v: "extend", adj: "extensive", adv: "extensively" },
  fabricate: { n: "fabrication", v: "fabricate" },
  facilitate: { n: "facilitation", v: "facilitate" },
  feasible: { n: "feasibility", adj: "feasible" },
  fluctuate: { n: "fluctuation", v: "fluctuate" },
  formidable: { adj: "formidable", adv: "formidably" },
  fragile: { n: "fragility", adj: "fragile" },
  fundamental: { adj: "fundamental", adv: "fundamentally" },
  generate: { n: "generation", v: "generate" },
  genuine: { n: "genuineness", adj: "genuine", adv: "genuinely" },
  gratitude: { n: "gratitude", adj: "grateful", adv: "gratefully" },
  hinder: { n: "hindrance", v: "hinder" },
  hypothesis: { n: "hypothesis", v: "hypothesize", adj: "hypothetical", adv: "hypothetically" },
  ideology: { n: "ideology", adj: "ideological", adv: "ideologically" },
  illustrate: { n: "illustration", v: "illustrate", adj: "illustrative" },
  imminent: { n: "imminence", adj: "imminent", adv: "imminently" },
  impartial: { n: "impartiality", adj: "impartial", adv: "impartially" },
  implement: { n: "implementation", v: "implement" },
  imply: { n: "implication", v: "imply", adj: "implicit" },
  impose: { n: "imposition", v: "impose", adj: "imposing" },
  incentive: { n: "incentive", v: "incentivize" },
  incline: { n: "inclination", v: "incline", adj: "inclined" },
  incorporate: { n: "incorporation", v: "incorporate" },
  inevitable: { n: "inevitability", adj: "inevitable", adv: "inevitably" },
  infer: { n: "inference", v: "infer", adj: "inferential" },
  inherent: { adj: "inherent", adv: "inherently" },
  initiate: { n: "initiative", v: "initiate", adj: "initial" },
  innovative: { n: "innovation", v: "innovate", adj: "innovative" },
  intricate: { n: "intricacy", adj: "intricate", adv: "intricately" },
  intrinsic: { adj: "intrinsic", adv: "intrinsically" },
  intuition: { n: "intuition", adj: "intuitive", adv: "intuitively" },
  justify: { n: "justification", v: "justify", adj: "justifiable" },
  legitimate: { n: "legitimacy", v: "legitimize", adj: "legitimate", adv: "legitimately" },
  lucrative: { adj: "lucrative", adv: "lucratively" },
  meticulous: { adj: "meticulous", adv: "meticulously" },
  mitigate: { n: "mitigation", v: "mitigate", adj: "mitigating" },
  notorious: { n: "notoriety", adj: "notorious", adv: "notoriously" },
  nurture: { n: "nurture", v: "nurture", adj: "nurturing" },
  objective: { n: "objectivity", adj: "objective", adv: "objectively" },
  obsolete: { n: "obsolescence", adj: "obsolete" },
  ominous: { adj: "ominous", adv: "ominously" },
  optimal: { n: "optimization", v: "optimize", adj: "optimal" },
  peculiar: { n: "peculiarity", adj: "peculiar", adv: "peculiarly" },
  perceive: { n: "perception", v: "perceive", adj: "perceptive" },
  perpetual: { v: "perpetuate", adj: "perpetual", adv: "perpetually" },
  persistent: { n: "persistence", v: "persist", adj: "persistent", adv: "persistently" },
  plausible: { n: "plausibility", adj: "plausible", adv: "plausibly" },
  pragmatic: { n: "pragmatism", adj: "pragmatic", adv: "pragmatically" },
  precede: { n: "precedence", v: "precede", adj: "preceding" },
  predominant: { v: "predominate", adj: "predominant", adv: "predominantly" },
  prevail: { n: "prevalence", v: "prevail", adj: "prevalent" },
  profound: { n: "profundity", adj: "profound", adv: "profoundly" },
  prohibit: { n: "prohibition", v: "prohibit", adj: "prohibitive" },
  prominent: { n: "prominence", adj: "prominent", adv: "prominently" },
  prospective: { n: "prospect", adj: "prospective", adv: "prospectively" },
  provoke: { n: "provocation", v: "provoke", adj: "provocative" },
  prudent: { n: "prudence", adj: "prudent", adv: "prudently" },
  rational: { n: "rationality", v: "rationalize", adj: "rational", adv: "rationally" },
  reconcile: { n: "reconciliation", v: "reconcile" },
  redundant: { n: "redundancy", adj: "redundant" },
  refute: { n: "refutation", v: "refute" },
  reinforce: { n: "reinforcement", v: "reinforce" },
  reluctant: { n: "reluctance", adj: "reluctant", adv: "reluctantly" },
  remarkable: { adj: "remarkable", adv: "remarkably" },
  resilient: { n: "resilience", adj: "resilient" },
  resolve: { n: "resolution", v: "resolve", adj: "resolute", adv: "resolutely" },
  retain: { n: "retention", v: "retain" },
  retrieve: { n: "retrieval", v: "retrieve" },
  rigorous: { n: "rigor", adj: "rigorous", adv: "rigorously" },
  robust: { n: "robustness", adj: "robust", adv: "robustly" },
  scrutiny: { n: "scrutiny", v: "scrutinize" },
  simultaneous: { adj: "simultaneous", adv: "simultaneously" },
  skeptical: { n: "skepticism", adj: "skeptical", adv: "skeptically" },
  sophisticated: { n: "sophistication", adj: "sophisticated" },
  spontaneous: { n: "spontaneity", adj: "spontaneous", adv: "spontaneously" },
  stagnant: { n: "stagnation", v: "stagnate", adj: "stagnant" },
  subtle: { n: "subtlety", adj: "subtle", adv: "subtly" },
  sufficient: { n: "sufficiency", v: "suffice", adj: "sufficient", adv: "sufficiently" },
  supplement: { n: "supplement", v: "supplement", adj: "supplementary" },
  suppress: { n: "suppression", v: "suppress" },
  susceptible: { n: "susceptibility", adj: "susceptible" },
  sustain: { n: "sustainability", v: "sustain", adj: "sustainable" },
  tangible: { adj: "tangible", adv: "tangibly" },
  tedious: { n: "tedium", adj: "tedious", adv: "tediously" },
  tentative: { adj: "tentative", adv: "tentatively" },
  thorough: { n: "thoroughness", adj: "thorough", adv: "thoroughly" },
  transparent: { n: "transparency", adj: "transparent", adv: "transparently" },
  trivial: { n: "triviality", v: "trivialize", adj: "trivial" },
  ubiquitous: { n: "ubiquity", adj: "ubiquitous", adv: "ubiquitously" },
  unanimous: { n: "unanimity", adj: "unanimous", adv: "unanimously" },
  undertake: { n: "undertaking", v: "undertake" },
  versatile: { n: "versatility", adj: "versatile" },
  viable: { n: "viability", adj: "viable", adv: "viably" },
  vivid: { n: "vividness", adj: "vivid", adv: "vividly" },
  diplomatic: { n: "diplomacy", adj: "diplomatic", adv: "diplomatically" },
  discern: { n: "discernment", v: "discern", adj: "discernible" },
  inquiry: { n: "inquiry", v: "inquire" },
  compelling: { v: "compel", adj: "compelling" },
  conscientious: { n: "conscientiousness", adj: "conscientious", adv: "conscientiously" },
  vulnerable: { n: "vulnerability", adj: "vulnerable" },
  // a few intermediate words with useful families
  decide: { n: "decision", v: "decide", adj: "decisive", adv: "decisively" },
  explain: { n: "explanation", v: "explain", adj: "explanatory" },
  suggest: { n: "suggestion", v: "suggest", adj: "suggestive" },
  prepare: { n: "preparation", v: "prepare", adj: "prepared" },
  improve: { n: "improvement", v: "improve", adj: "improved" },
  depend: { n: "dependence", v: "depend", adj: "dependent" },
  apologize: { n: "apology", v: "apologize", adj: "apologetic" },
  necessary: { n: "necessity", adj: "necessary", adv: "necessarily" },
  convenient: { n: "convenience", adj: "convenient", adv: "conveniently" },
  comfortable: { n: "comfort", adj: "comfortable", adv: "comfortably" }
};
